/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2026 Nebula Matrix Limited.
 */

#ifndef _NBL_HW_LEONIS_H_
#define _NBL_HW_LEONIS_H_

#include <linux/types.h>

#include "../../nbl_include/nbl_include.h"
#include "../nbl_hw_reg.h"

#define NBL_DRIVER_STATUS_REG			0x1300444
#define NBL_DRIVER_STATUS_BIT			16

/*  ----------  REG BASE ADDR  ----------  */
/* Interface modules base addr */
#define NBL_INTF_HOST_PCOMPLETER_BASE		0x00f08000
#define NBL_INTF_HOST_PADPT_BASE		0x00f4c000
#define NBL_INTF_HOST_MAILBOX_BASE		0x00fb0000
#define NBL_INTF_HOST_PCIE_BASE			0X01504000
/* DP modules base addr */
#define NBL_DP_USTORE_BASE			0x00104000
#define NBL_DP_UQM_BASE				0x00114000
#define NBL_DP_UPED_BASE			0x0015c000
#define NBL_DP_UVN_BASE				0x00244000
#define NBL_DP_DSCH_BASE			0x00404000
#define NBL_DP_SHAPING_BASE			0x00504000
#define NBL_DP_DVN_BASE				0x00514000
#define NBL_DP_DSTORE_BASE			0x00704000
#define NBL_DP_DPED_BASE			0x0075c000
/*  --------  MAILBOX BAR2 -----  */
#define NBL_MAILBOX_NOTIFY_ADDR			0x00000000
#define NBL_MAILBOX_QINFO_CFG_RX_TABLE_ADDR	0x10
#define NBL_MAILBOX_QINFO_CFG_TX_TABLE_ADDR	0x20

/*  --------  MAILBOX  --------  */

/* mailbox BAR qinfo_cfg_table */
#define MAILBOX_QINFO_CFG_TABLE_DWLEN	4
/* data[2] */
#define NBL_MAILBOX_QINFO_CFG_QUEUE_SIZE_BWID_MASK	GENMASK(3, 0)
/* data[3] */
#define NBL_MAILBOX_QINFO_CFG_QUEUE_RST_MASK		BIT(0)
#define NBL_MAILBOX_QINFO_CFG_QUEUE_EN_MASK		BIT(1)
#define NBL_MAILBOX_QINFO_CFG_DIF_ERR_MASK		BIT(2)
#define NBL_MAILBOX_QINFO_CFG_PTR_ERR_MASK		BIT(3)
struct nbl_mailbox_qinfo_cfg_table {
	u32 data[MAILBOX_QINFO_CFG_TABLE_DWLEN];
};

/*  --------  MAILBOX BAR0 -----  */
/* mailbox qinfo_map_table */
#define NBL_MAILBOX_QINFO_MAP_REG_ARR(func_id) \
	(NBL_INTF_HOST_MAILBOX_BASE + 0x00001000 + (func_id) * sizeof(u32))

/* MAILBOX qinfo_map_table */
#define NBL_MAILBOX_QINFO_MAP_FUNCTION_MASK		GENMASK(2, 0)
#define NBL_MAILBOX_QINFO_MAP_DEVID_MASK		GENMASK(7, 3)
#define NBL_MAILBOX_QINFO_MAP_BUS_MASK			GENMASK(15, 8)
#define NBL_MAILBOX_QINFO_MAP_MSIX_IDX_MASK		GENMASK(28, 16)
#define NBL_MAILBOX_QINFO_MAP_MSIX_IDX_VALID_MASK	BIT(29)

/*  --------  HOST_PCIE  --------  */
#define NBL_PCIE_HOST_K_PF_MASK_REG (NBL_INTF_HOST_PCIE_BASE + 0x00001004)
#define NBL_PCIE_HOST_TL_CFG_BUSDEV (NBL_INTF_HOST_PCIE_BASE + 0x11040)

#define NBL_PCIE_BUS_MASK	GENMASK(12, 5)

/*  --------  HOST_PADPT  --------  */
#define NBL_HOST_PADPT_HOST_CFG_FC_PD_DN (NBL_INTF_HOST_PADPT_BASE + 0x00000160)
#define NBL_HOST_PADPT_HOST_CFG_FC_PH_DN (NBL_INTF_HOST_PADPT_BASE + 0x00000164)
#define NBL_HOST_PADPT_HOST_CFG_FC_NPH_DN \
	(NBL_INTF_HOST_PADPT_BASE + 0x0000016C)
#define NBL_HOST_PADPT_HOST_CFG_FC_CPLH_UP \
	(NBL_INTF_HOST_PADPT_BASE + 0x00000170)

#define NBL_HOST_PADPT_CFG_FC_CPLH_UP_VAL      0x10400
#define NBL_HOST_PADPT_CFG_FC_PD_DN_VAL        0x10080
#define NBL_HOST_PADPT_CFG_FC_PH_DN_VAL        0x10010
#define NBL_HOST_PADPT_CFG_FC_NPH_DN_VAL       0x10010
/* host_padpt host_msix_info */
#define NBL_PADPT_HOST_MSIX_INFO_REG_ARR(vector_id) \
	(NBL_INTF_HOST_PADPT_BASE + 0x00010000 +    \
	 (vector_id) * sizeof(struct nbl_host_msix_info))

#define NBL_HOST_MSIX_INFO_DWLEN	2
/* data[0] */
#define NBL_HOST_MSIX_INFO_INTRL_PNUM_MASK GENMASK(15, 0)
#define NBL_HOST_MSIX_INFO_INTRL_RATE_MASK GENMASK(31, 16)
/* data[1] */
#define NBL_HOST_MSIX_INFO_FUNCTION_MASK GENMASK(2, 0)
#define NBL_HOST_MSIX_INFO_DEVID_MASK GENMASK(7, 3)
#define NBL_HOST_MSIX_INFO_BUS_MASK GENMASK(15, 8)
#define NBL_HOST_MSIX_INFO_VALID_MASK BIT(16)
#define NBL_HOST_MSIX_INFO_MSIX_MASK_EN_MASK BIT(17)
struct nbl_host_msix_info {
	u32 data[NBL_HOST_MSIX_INFO_DWLEN];
};

/*  --------  HOST_PCOMPLETER  --------  */
/* pcompleter_host function_msix_map_table */
#define NBL_PCOMPLETER_FUNCTION_MSIX_MAP_REG_ARR(i)   \
	(NBL_INTF_HOST_PCOMPLETER_BASE + 0x00004000 + \
	 (i) * sizeof(struct nbl_function_msix_map))
#define NBL_PCOMPLETER_HOST_MSIX_FID_TABLE(i) \
	(NBL_INTF_HOST_PCOMPLETER_BASE + 0x0003a000 + (i) * sizeof(u32))

#define NBL_PCOMPLETER_HOST_MSIX_FID_TABLE_FID_MASK  GENMASK(9, 0)
#define NBL_PCOMPLETER_HOST_MSIX_FID_TABLE_VLD_MASK  BIT(10)

#define NBL_FUNC_MSIX_MAP_DWLEN		4
/* data[2] */
#define NBL_FUNCTION_MSIX_MAP_FUNCTION_MASK GENMASK(2, 0)
#define NBL_FUNCTION_MSIX_MAP_DEVID_MASK GENMASK(7, 3)
#define NBL_FUNCTION_MSIX_MAP_BUS_MASK GENMASK(15, 8)
#define NBL_FUNCTION_MSIX_MAP_VALID_MASK BIT(16)
struct nbl_function_msix_map {
	u32 data[NBL_FUNC_MSIX_MAP_DWLEN];
};

/*  ----------  DPED  ----------  */
#define NBL_DPED_VLAN_OFFSET		(NBL_DP_DPED_BASE + 0x000003F4)
#define NBL_DPED_DSCP_OFFSET_0		(NBL_DP_DPED_BASE + 0x000003F8)
#define NBL_DPED_DSCP_OFFSET_1		(NBL_DP_DPED_BASE + 0x000003FC)
/* DPED hw_edt_prof/ UPED hw_edt_prof */

#define NBL_DPED_L4_CK_CMD_40_ADDR	(NBL_DP_DPED_BASE + 0x00000338)

#define NBL_DPED_L4_CK_CMD_40_EN_MASK		BIT(31)

/*  ----------  UPED  ----------  */
/* UPED uped_hw_edt_prof */
#define NBL_UPED_HW_EDT_PROF_TABLE(i) \
	(NBL_DP_UPED_BASE + 0x00001000 + (i) * sizeof(u32))
#define NBL_UPED_V4_TCP_IDX		5
#define NBL_UPED_V6_TCP_IDX		6
#define NBL_PED_HW_EDIT_PROFILE_L3_LEN_MASK GENMASK(3, 2)

/*  ----------  DSCH  ----------  */
#define NBL_DSCH_PSHA_EN_MASK  GENMASK(3, 0)
/* DSCH dsch maxqid */
#define NBL_DSCH_HOST_QID_MAX (NBL_DP_DSCH_BASE + 0x00000118)
#define NBL_DSCH_HOST_QID_MAX_MASK GENMASK(10, 0)
#define NBL_DSCH_VN_QUANTA_ADDR (NBL_DP_DSCH_BASE + 0x00000134)

#define NBL_MAX_QUEUE_ID	0x7ff
#define NBL_HOST_QUANTA		0x8000
#define NBL_ECPU_QUANTA		0x1000

#define NBL_DSCH_VN_QUANTA_H_QUA_MASK GENMASK(15, 0)
#define NBL_DSCH_VN_QUANTA_E_QUA_MASK GENMASK(31, 16)

/*  ----------  DVN  ----------  */
/* DVN dvn_queue_table */
#define NBL_DVN_ECPU_QUEUE_NUM			(NBL_DP_DVN_BASE + 0x0000041C)
#define NBL_DVN_DESCREQ_NUM_CFG			(NBL_DP_DVN_BASE + 0x00000430)
#define NBL_DVN_DESC_WR_MERGE_TIMEOUT		(NBL_DP_DVN_BASE + 0x00000480)
#define NBL_DVN_DIF_REQ_RD_RO_FLAG		(NBL_DP_DVN_BASE + 0x0000045C)

#define DEFAULT_DVN_DESCREQ_NUMCFG		0x03
#define DEFAULT_DVN_100G_DESCREQ_NUMCFG		0x07

#define DEFAULT_DVN_DESC_WR_MERGE_TIMEOUT_MAX	0x3FF

/* spilit ring descreq_num 0:8,1:16 */
#define NBL_DVN_DESCREQ_NUM_CFG_AVRING_DESREQ_NUM_CFG_MASK BIT(0)
/* packet ring descreq_num
 * 0:8,1:12,2:16;3:20,4:24,5:26;6:32,7:32
 */
#define NBL_DVN_DESCREQ_NUM_CFG_PACKED_L1_NUM_MASK GENMASK(6, 4)

#define NBL_DVN_DESC_WR_MERGE_TIMEOUT_CFG_CYCLE_MASK GENMASK(9, 0)

#define NBL_DVN_DIF_REQ_RD_RO_FLAG_DESC_RO_EN_MASK BIT(0)
#define NBL_DVN_DIF_REQ_RD_RO_FLAG_DATA_RO_EN_MASK BIT(1)
#define NBL_DVN_DIF_REQ_RD_RO_FLAG_AVRING_RO_EN_MASK BIT(2)

/*  ----------  UVN  ----------  */
/* UVN uvn_queue_table */

#define NBL_UVN_DESC_RD_WAIT			(NBL_DP_UVN_BASE + 0x0000020C)
#define NBL_UVN_QUEUE_ERR_MASK			(NBL_DP_UVN_BASE + 0x00000224)
#define NBL_UVN_ECPU_QUEUE_NUM			(NBL_DP_UVN_BASE + 0x0000023C)
#define NBL_UVN_DESC_WR_TIMEOUT			(NBL_DP_UVN_BASE + 0x00000214)
#define NBL_UVN_DIF_REQ_RO_FLAG			(NBL_DP_UVN_BASE + 0x00000250)
#define NBL_UVN_DESC_PREFETCH_INIT		(NBL_DP_UVN_BASE + 0x00000204)
#define NBL_UVN_DESC_PREFETCH_NUM		4

#define NBL_UVN_DIF_REQ_RO_FLAG_AVAIL_RD_MASK BIT(0)
#define NBL_UVN_DIF_REQ_RO_FLAG_DESC_RD_MASK BIT(1)
#define NBL_UVN_DIF_REQ_RO_FLAG_PKT_WR_MASK BIT(2)
#define NBL_UVN_DIF_REQ_RO_FLAG_DESC_WR_MASK BIT(3)

#define NBL_UVN_DESC_WR_TIMEOUT_NUM_MASK GENMASK(14, 0)

#define NBL_UVN_QUEUE_ERR_MASK_DIF_ERR_MASK BIT(5)

#define NBL_UVN_DESC_PREFETCH_INIT_NUM_MASK GENMASK(7, 0)
#define NBL_UVN_DESC_PREFETCH_INIT_SEL_MASK BIT(16)

#define NBL_UVN_DESC_WR_TIMEOUT_VAL 0x12c
/* 200us = 200000ns / 1.67ns per tick = 119760 ticks */
#define NBL_UVN_DESC_RD_WAIT_TICKS 119760

/*  --------  USTORE  --------  */
#define NBL_USTORE_PKT_LEN_ADDR (NBL_DP_USTORE_BASE + 0x00000108)
#define NBL_USTORE_PORT_DROP_TH_REG_ARR(port_id) \
	(NBL_DP_USTORE_BASE + 0x00000150 + (port_id) * sizeof(u32))
#define NBL_USTORE_BUF_PORT_DROP_PKT(eth_id) \
	(NBL_DP_USTORE_BASE + 0x00002500 + (eth_id) * sizeof(u32))
#define NBL_USTORE_BUF_PORT_TRUN_PKT(eth_id) \
	(NBL_DP_USTORE_BASE + 0x00002540 + (eth_id) * sizeof(u32))

#define NBL_USTORE_SINGLE_ETH_DROP_TH		0xC80
#define NBL_USTORE_DUAL_ETH_DROP_TH		0x640
#define NBL_USTORE_QUAD_ETH_DROP_TH		0x320

/* USTORE pkt_len */
#define NBL_USTORE_PKT_LEN_MIN_MASK GENMASK(6, 0)

/* USTORE port_drop_th */
#define NBL_USTORE_PORT_DROP_TH_DISC_TH_MASK GENMASK(11, 0)
#define NBL_USTORE_PORT_DROP_TH_EN_MASK BIT(31)

/* UQM*/
#define NBL_UQM_QUE_TYPE			(NBL_DP_UQM_BASE + 0x0000013c)
#define NBL_UQM_DROP_PKT_CNT			(NBL_DP_UQM_BASE + 0x000009C0)
#define NBL_UQM_DROP_PKT_SLICE_CNT		(NBL_DP_UQM_BASE + 0x000009C4)
#define NBL_UQM_DROP_PKT_LEN_ADD_CNT		(NBL_DP_UQM_BASE + 0x000009C8)
#define NBL_UQM_DROP_HEAD_PNTR_ADD_CNT		(NBL_DP_UQM_BASE + 0x000009CC)
#define NBL_UQM_DROP_WEIGHT_ADD_CNT		(NBL_DP_UQM_BASE + 0x000009D0)
#define NBL_UQM_PORT_DROP_PKT_CNT		(NBL_DP_UQM_BASE + 0x000009D4)
#define NBL_UQM_PORT_DROP_PKT_SLICE_CNT		(NBL_DP_UQM_BASE + 0x000009F4)
#define NBL_UQM_PORT_DROP_PKT_LEN_ADD_CNT	(NBL_DP_UQM_BASE + 0x00000A14)
#define NBL_UQM_PORT_DROP_HEAD_PNTR_ADD_CNT	(NBL_DP_UQM_BASE + 0x00000A34)
#define NBL_UQM_PORT_DROP_WEIGHT_ADD_CNT	(NBL_DP_UQM_BASE + 0x00000A54)
#define NBL_UQM_FWD_DROP_CNT			(NBL_DP_UQM_BASE + 0x00000A80)
#define NBL_UQM_DPORT_DROP_CNT			(NBL_DP_UQM_BASE + 0x00000B74)

#define NBL_UQM_PORT_DROP_DEPTH			6
#define NBL_UQM_DPORT_DROP_DEPTH		16

/*  ---------  SHAPING  ---------  */

/* Shaping rate unit: 1 = 1 Mbit/s.
 * e.g. 100000 = 100 Gbit/s, 25000 = 25 Gbit/s.
 */
#define NBL_LR_LEONIS_NET_BUCKET_DEPTH		9600
#define NBL_SHAPING_DPORT_ADDR (NBL_DP_SHAPING_BASE + 0x700)
#define NBL_SHAPING_DPORT_DWLEN 4
#define NBL_SHAPING_DPORT_REG(r) \
	(NBL_SHAPING_DPORT_ADDR + (NBL_SHAPING_DPORT_DWLEN * 4) * (r))
#define NBL_SHAPING_DVN_DPORT_ADDR (NBL_DP_SHAPING_BASE + 0x750)
#define NBL_SHAPING_DVN_DPORT_DWLEN 4
#define NBL_SHAPING_DVN_DPORT_REG(r) \
	(NBL_SHAPING_DVN_DPORT_ADDR + (NBL_SHAPING_DVN_DPORT_DWLEN * 4) * (r))
#define NBL_DSCH_PSHA_EN_ADDR (NBL_DP_DSCH_BASE + 0x00000314)
#define NBL_SHAPING_NET_ADDR (NBL_DP_SHAPING_BASE + 0x1800)
#define NBL_SHAPING_NET_DWLEN 4
#define NBL_SHAPING_NET_REG(r) \
	(NBL_SHAPING_NET_ADDR + (NBL_SHAPING_NET_DWLEN * 4) * (r))

#define NBL_DPORT_VALID_MASK		GENMASK_ULL(0, 0)
#define NBL_DPORT_DEPTH_MASK		GENMASK_ULL(19, 1)
#define NBL_DPORT_CIR_MASK		GENMASK_ULL(38, 20)
#define NBL_DPORT_PIR_MASK		GENMASK_ULL(57, 39)
#define NBL_DPORT_CBS_MASK_LOW		GENMASK_ULL(63, 58)
#define NBL_DPORT_CBS_MASK_HIGH		GENMASK_ULL(14, 0)
#define NBL_DPORT_PBS_MASK		GENMASK_ULL(35, 15)

/* SHAPING shaping_net */
struct nbl_shaping_net_u {
	u32 data[NBL_SHAPING_NET_DWLEN];
};

struct nbl_shaping_dport_u {
	u32 data[NBL_SHAPING_DPORT_DWLEN];
};

struct nbl_shaping_dvn_dport_u {
	u32 data[NBL_SHAPING_DVN_DPORT_DWLEN];
};

/*  --------  DSTORE  --------  */
#define NBL_DSTORE_D_DPORT_FC_TH_ADDR  (NBL_DP_DSTORE_BASE + 0x00000600)
#define NBL_DSTORE_D_DPORT_FC_TH_DEPTH 5
#define NBL_DSTORE_D_DPORT_FC_TH_WIDTH 32
#define NBL_DSTORE_D_DPORT_FC_TH_DWLEN 1

#define NBL_DSTORE_D_DPORT_FC_XOFF_TH_MASK GENMASK(10, 0)
#define NBL_DSTORE_D_DPORT_FC_XON_TH_MASK GENMASK(26, 16)
#define NBL_DSTORE_D_DPORT_FC_FC_EN_MASK BIT(31)

#define NBL_DSTORE_D_DPORT_FC_TH_REG(r)  \
	(NBL_DSTORE_D_DPORT_FC_TH_ADDR + \
	 (NBL_DSTORE_D_DPORT_FC_TH_DWLEN * 4) * (r))
#define NBL_DSTORE_PORT_DROP_TH_ADDR (NBL_DP_DSTORE_BASE + 0x00000150)
#define NBL_DSTORE_PORT_DROP_TH_DEPTH 6
#define NBL_DSTORE_PORT_DROP_TH_WIDTH 32
#define NBL_DSTORE_PORT_DROP_TH_DWLEN 1

#define NBL_DSTORE_PORT_DROP_EN_MASK BIT(31)

#define NBL_DSTORE_DROP_XOFF_TH			0xC8
#define NBL_DSTORE_DROP_XON_TH			0x64

#define NBL_DSTORE_DROP_XOFF_TH_100G		0x1F4
#define NBL_DSTORE_DROP_XON_TH_100G		0x12C

#define NBL_DSTORE_DISC_BP_TH (NBL_DP_DSTORE_BASE + 0x00000630)

#define NBL_DSTORE_DISC_BP_TH_EN_MASK BIT(31)

#define NBL_DSTORE_PORT_DROP_TH_REG(r)  \
	(NBL_DSTORE_PORT_DROP_TH_ADDR + \
	 (NBL_DSTORE_PORT_DROP_TH_DWLEN * 4) * (r))

#define NBL_FW_BOARD_CONFIG			0x200
#define NBL_FW_BOARD_DW3_OFFSET			(NBL_FW_BOARD_CONFIG + 12)
#define NBL_FW_BOARD_DW6_OFFSET			(NBL_FW_BOARD_CONFIG + 24)

#define NBL_FW_BOARD_DW3_PORT_TYPE_MASK BIT(0)
#define NBL_FW_BOARD_DW3_PORT_NUM_MASK GENMASK(7, 1)
#define NBL_FW_BOARD_DW3_PORT_SPEED_MASK GENMASK(9, 8)
#define NBL_FW_BOARD_DW3_GPIO_TYPE_MASK GENMASK(12, 10)
#define NBL_FW_BOARD_DW3_P4_VERSION_MASK GENMASK(13, 13)

#define NBL_FW_BOARD_DW6_LANE_BITMAP_MASK GENMASK(7, 0)
#define NBL_FW_BOARD_DW6_ETH_BITMAP_MASK GENMASK(15, 8)

#define NBL_LEONIS_QUIRKS_OFFSET	0x00000140
#define NBL_BAR2_MAX_LEN		0x300
#endif
