/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _BPF_CGROUP_TYPES_H
#define _BPF_CGROUP_TYPES_H

enum bpf_cgroup_storage_type {
	BPF_CGROUP_STORAGE_SHARED,
	BPF_CGROUP_STORAGE_PERCPU,
	__BPF_CGROUP_STORAGE_MAX
};

#define MAX_BPF_CGROUP_STORAGE_TYPE __BPF_CGROUP_STORAGE_MAX

#endif
