/* SPDX-License-Identifier: GPL-2.0 OR MIT */
/*
 * Copyright (C) 2024 StarFive Technology Co., Ltd.
 * Author: Changhuang Liang <changhuang.liang@starfivetech.com>
 *
 */

#ifndef __DT_BINDINGS_RESET_STARFIVE_JHB100_CRG_H__
#define __DT_BINDINGS_RESET_STARFIVE_JHB100_CRG_H__

/* SYS0CRG resets */
#define JHB100_SYS0RST_RESOURCE_ARB					0
#define JHB100_SYS0RST_SYS0_IOMUX_PRESETN				1
#define JHB100_SYS0RST_SYS0H_IOMUX_PRESETN				2
#define JHB100_SYS0RST_RST_ADAPTOR_TIMEOUT_RSTN				3
#define JHB100_SYS0RST_BMCPCIERP_RSTN_BUS				4
#define JHB100_SYS0RST_BMCPCIERP_RSTN_CRG				5
#define JHB100_SYS0RST_HOSTSS0_RSTN_BUS_ESPI				6
#define JHB100_SYS0RST_HOSTSS0_RSTN_BUS_PCIE				7
#define JHB100_SYS0RST_HOSTSS0_RSTN_CRG					8
#define JHB100_SYS0RST_BMCPERIPH2_RSTN_CRG				9
#define JHB100_SYS0RST_BMCPERIPH2_RSTN_BUS				10
#define JHB100_SYS0RST_VCE_RSTN_CRG					11
#define JHB100_SYS0RST_VCE_RSTN_BUS					12
#define JHB100_SYS0RST_BMCUSB_RSTN_BUS					13
#define JHB100_SYS0RST_BMCUSB_RSTN_CRG					14

#endif /* __DT_BINDINGS_RESET_STARFIVE_JHB100_CRG_H__ */
