# SPDX-License-Identifier: GPL-2.0
all:

TEST_PROGS_EXTENDED := ftracetest
TEST_PROGS := ftracetest-ktap boottime-ktap
TEST_FILES := test.d settings boottime
EXTRA_CLEAN := $(OUTPUT)/logs/*

TEST_GEN_FILES := poll

include ../lib.mk
