# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_NET_DSA_MICROCHIP_LAN9645X) += mchp-lan9645x.o

mchp-lan9645x-objs := \
	lan9645x_mac.o \
	lan9645x_main.o \
	lan9645x_npi.o \
	lan9645x_phylink.o \
	lan9645x_port.o \
	lan9645x_vlan.o \
