#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2026 Google LLC
#
# loader_setup.sh - Light skeleton data extraction helper for selftests/bpf
#
# This script parses an autogenerated light skeleton header (.lskel.h) produced
# by bpftool ('bpftool gen skeleton -L'). It extracts the embedded loader data
# ('opts_data') and loader BPF instructions ('opts_insn') string literals and
# generates a C header file containing:
#   - loader_test_opts_data[]: Data for the '__loader.map' section.
#   - loader_test_opts_data_sz: Size of opts_data.
#   - loader_test_opts_insn[]: Instructions for the '__loader.prog' section.
#   - loader_test_opts_insn_sz: Size of opts_insn.
#
# These extracted sections are used by the 'loader_load_fd' selftest to populate
# an in-memory ELF object file for kernel 'BPF_LOADER_LOAD_FD' testing.
#
# Usage:
#   loader_setup.sh <input_lskel.h> <output_data.h>

INPUT="$1"
OUTPUT="$2"

if [ -z "$INPUT" ] || [ -z "$OUTPUT" ]; then
	echo "Usage: $0 <input_lskel.h> <output_data.h>" >&2
	exit 1
fi

awk -v input="$INPUT" '
BEGIN {
	print "/* Generated from " input " */"
	in_data = 0
	in_insn = 0
}
/opts_data\[\]/ {
	in_data = 1
	sub(/^.*opts_data\[\][^="]*=\s*"/, "")
	printf "static const char test_loader_opts_data[] __attribute__((__aligned__(8))) = \""
}
in_data {
	if (index($0, "\";") > 0) {
		sub(/";.*/, "")
		print $0 "\";"
		print "static const size_t test_loader_opts_data_sz = " \
		      "sizeof(test_loader_opts_data) - 1;\n"
		in_data = 0
	} else {
		print $0
	}
}
/opts_insn\[\]/ {
	in_insn = 1
	sub(/^.*opts_insn\[\][^="]*=\s*"/, "")
	printf "static const char test_loader_opts_insn[] __attribute__((__aligned__(8))) = \""
}
in_insn {
	if (index($0, "\";") > 0) {
		sub(/";.*/, "")
		print $0 "\";"
		print "static const size_t test_loader_opts_insn_sz = " \
		      "sizeof(test_loader_opts_insn) - 1;"
		in_insn = 0
	} else {
		print $0
	}
}
' "$INPUT" > "$OUTPUT"
