# SPDX-License-Identifier: GPL-2.0
# Rules to build the BPF objects and skeletons of one build flavor,
# shared by the main Makefile (which instantiates them for the default
# flavor, so that bench, test_maps, xskxceiver, test_cpp and the
# install rule can depend on the exact files they consume) and by
# Makefile.runner (which instantiates them for the flavored runner
# instances in their own output directories).
#
# Parameters (variables defined by the includer):
#   RDIR             output directory of this flavor
#   FLAVOR           flavor name, empty for the default
#   BINARY           runner binary name, for build-log messages
#   BPF_CC           BPF compiler
#   BPF_CC_MSG       build-log tag (CLNG-BPF/GCC-BPF)
#   BPF_CC_FLAGS     per-flavor compiler flags
#   BPF_SYS_INCLUDES system include flags for $(BPF_CC)
#   BPF_DEFINES      extra defines (-DENABLE_ATOMICS_TESTS)
#
# The default flavor's rules are instantiated identically by the main
# Makefile and by the unflavored runner sub-makes; the main Makefile
# lists every skeleton and BPF object as a prerequisite of the runner
# delegation rules, so the files are always fresh by the time a runner
# sub-make re-evaluates them.

# ---------------------------------------------------------------------
# BPF objects and skeletons
# ---------------------------------------------------------------------

ifneq ($(BPF_CC),)

BPF_SRCS := $(notdir $(wildcard progs/*.c))
BPF_OBJS := $(patsubst %.c,$(RDIR)/%.bpf.o,$(BPF_SRCS))

LSKELS := fexit_sleep.c trace_printk.c trace_vprintk.c map_ptr_kern.c 	\
	core_kern.c core_kern_overflow.c test_ringbuf.c			\
	test_ringbuf_n.c test_ringbuf_map_key.c test_ringbuf_write.c    \
	test_ringbuf_overwrite.c

LSKELS_SIGNED := fentry_test.c fexit_test.c atomics.c

SKEL_BLACKLIST := btf__% test_pinning_invalid.c test_sk_assign.c \
		  $(LSKELS) $(LSKELS_SIGNED)

# Skeletons made by linking multiple BPF objects together. The %-deps
# mapping is the only hand-maintained metadata: it cannot be derived from
# the sources.
test_static_linked.skel.h-deps := test_static_linked1.bpf.o test_static_linked2.bpf.o
linked_funcs.skel.h-deps := linked_funcs1.bpf.o linked_funcs2.bpf.o
linked_vars.skel.h-deps := linked_vars1.bpf.o linked_vars2.bpf.o
linked_maps.skel.h-deps := linked_maps1.bpf.o linked_maps2.bpf.o
# In the subskeleton case, we want the test_subskeleton_lib.subskel.h file
# but that's created as a side-effect of the skel.h generation.
test_subskeleton.skel.h-deps := test_subskeleton_lib2.bpf.o test_subskeleton_lib.bpf.o test_subskeleton.bpf.o
test_subskeleton_lib.skel.h-deps := test_subskeleton_lib2.bpf.o test_subskeleton_lib.bpf.o
test_usdt.skel.h-deps := test_usdt.bpf.o test_usdt_multispec.bpf.o
tracing_multi.skel.h-deps := tracing_multi_attach.bpf.o tracing_multi_check.bpf.o
tracing_multi_module.skel.h-deps := tracing_multi_attach_module.bpf.o tracing_multi_check.bpf.o
tracing_multi_intersect.skel.h-deps := tracing_multi_intersect_attach.bpf.o tracing_multi_check.bpf.o
tracing_multi_session.skel.h-deps := tracing_multi_session_attach.bpf.o tracing_multi_check.bpf.o

LINKED_SKELS := test_static_linked.skel.h linked_funcs.skel.h		\
		linked_vars.skel.h linked_maps.skel.h			\
		test_subskeleton.skel.h test_subskeleton_lib.skel.h	\
		test_usdt.skel.h tracing_multi.skel.h			\
		tracing_multi_module.skel.h				\
		tracing_multi_intersect.skel.h				\
		tracing_multi_session.skel.h

LINKED_BPF_SRCS := $(patsubst %.bpf.o,%.c,$(foreach skel,$(LINKED_SKELS),$($(skel)-deps)))

# Generate both light skeleton and libbpf skeleton for these
LSKELS_EXTRA := test_ksyms_module.c test_ksyms_weak.c kfunc_call_test.c \
	kfunc_call_test_subprog.c test_global_percpu_data.c

SKELS := $(patsubst %.c,$(RDIR)/%.skel.h,				\
	   $(filter-out $(SKEL_BLACKLIST) $(LINKED_BPF_SRCS),$(BPF_SRCS)))
LSKELS_H        := $(patsubst %.c,$(RDIR)/%.lskel.h,$(LSKELS) $(LSKELS_EXTRA))
LSKELS_SIGNED_H := $(patsubst %.c,$(RDIR)/%.lskel.h,$(LSKELS_SIGNED))
LINKED_SKELS_H  := $(addprefix $(RDIR)/,$(LINKED_SKELS))
ALL_SKELS := $(SKELS) $(LSKELS_H) $(LSKELS_SIGNED_H) $(LINKED_SKELS_H)

HEADERS_FOR_BPF_OBJS := $(wildcard $(BPFDIR)/*.bpf.h)			\
			$(wildcard $(CURDIR)/libarena/include/*.[ch])	\
			$(addprefix $(BPFDIR)/,	bpf_core_read.h		\
						bpf_endian.h		\
						bpf_helpers.h		\
						bpf_tracing.h)

# Per-source BPF compilation flag overrides ($<-CFLAGS / $<-$(FLAVOR)-CFLAGS).
# GCC cannot disable "declaration of anonymous struct in parameter list"
# warnings triggered by these (technically legal) test programs.
progs/btf_dump_test_case_bitfields.c-bpf_gcc-CFLAGS := -Wno-error
progs/btf_dump_test_case_namespacing.c-bpf_gcc-CFLAGS := -Wno-error
progs/btf_dump_test_case_packing.c-bpf_gcc-CFLAGS := -Wno-error
progs/btf_dump_test_case_padding.c-bpf_gcc-CFLAGS := -Wno-error
progs/btf_dump_test_case_syntax.c-bpf_gcc-CFLAGS := -Wno-error

$(BPF_OBJS): $(RDIR)/%.bpf.o: progs/%.c progs/*.h			\
	     $(INCLUDE_DIR)/vmlinux.h $(HEADERS_FOR_BPF_OBJS)		\
	     | $(RDIR) $(BPFOBJ)
	$(call msg,$(BPF_CC_MSG),$(BINARY),$@)
	$(Q)$(BPF_CC) $(BPF_CFLAGS) $(BPF_SYS_INCLUDES) $(BPF_DEFINES)	\
		$($<-CFLAGS) $($<-$(FLAVOR)-CFLAGS)			\
		$(BPF_CC_FLAGS) -c $< -o $@ $(call skip_on_fail,BPF)

# gen_bpf_skel.sh picks the bpftool binary up from the environment.
export BPFTOOL
GEN_SKEL := ./gen_bpf_skel.sh

$(SKELS): $(RDIR)/%.skel.h: $(RDIR)/%.bpf.o $(BPFTOOL) $(GEN_SKEL) | $(RDIR)
	$(Q)$(call skip_if_missing,SKEL,$<,$(@:.skel.h=.subskel.h))	\
	printf '  %-8s%s %s\n' 'GEN-SKEL' ' [$(BINARY)]' '$(notdir $@)'; \
	$(GEN_SKEL) --name $*						\
		--skel $@ --subskel $(@:.skel.h=.subskel.h) $<		\
		$(call skip_on_fail,SKEL,$(@:.skel.h=.subskel.h))

$(LSKELS_H): $(RDIR)/%.lskel.h: $(RDIR)/%.bpf.o $(BPFTOOL) $(GEN_SKEL) | $(RDIR)
	$(Q)$(call skip_if_missing,SKEL,$<)				\
	printf '  %-8s%s %s\n' 'GEN-SKEL' ' [$(BINARY)]' '$(notdir $@)'; \
	$(GEN_SKEL) --name $*_lskel --lskel				\
		--skel $@ $< $(call skip_on_fail,SKEL)

$(LSKELS_SIGNED_H): $(RDIR)/%.lskel.h: $(RDIR)/%.bpf.o $(BPFTOOL)	\
		    $(GEN_SKEL) $(PRIVATE_KEY) $(VERIFICATION_CERT) | $(RDIR)
	$(Q)$(call skip_if_missing,SKEL,$<)				\
	printf '  %-8s%s %s\n' 'GEN-SKEL' ' [$(BINARY) (signed)]' '$(notdir $@)'; \
	PRIVATE_KEY=$(PRIVATE_KEY)					\
		VERIFICATION_CERT=$(VERIFICATION_CERT)			\
		$(GEN_SKEL) --sign --name $*_lskel			\
		--skel $@ $< $(call skip_on_fail,SKEL)

.SECONDEXPANSION:
$(LINKED_SKELS_H): $(RDIR)/%.skel.h: $$(addprefix $(RDIR)/,$$($$*.skel.h-deps)) \
		   $(BPFTOOL) $(GEN_SKEL) | $(RDIR)
	$(Q)$(call skip_if_missing,SKEL,$(addprefix $(RDIR)/,$($*.skel.h-deps)),$(@:.skel.h=.subskel.h)) \
	printf '  %-8s%s %s\n' 'LINK-BPF' ' [$(BINARY)]' '$(notdir $(@:.skel.h=.bpf.o))'; \
	printf '  %-8s%s %s\n' 'GEN-SKEL' ' [$(BINARY)]' '$(notdir $@)'; \
	$(GEN_SKEL) --name $*						\
		--skel $@ --subskel $(@:.skel.h=.subskel.h)		\
		$(addprefix $(RDIR)/,$($*.skel.h-deps))			\
		$(call skip_on_fail,SKEL,$(@:.skel.h=.subskel.h))

endif # BPF_CC
