/* SPDX-License-Identifier: GPL-2.0-only
 *
 * Copyright (c) 2022, MediaTek Inc.
 */

#ifndef __MTK_PCI_REG_H__
#define __MTK_PCI_REG_H__

#define REG_ATR_PCIE_WIN0_T0_SRC_ADDR_LSB	0x0600
#define REG_ATR_PCIE_WIN0_T0_SRC_ADDR_MSB	0x0604
#define REG_ATR_PCIE_WIN0_T0_TRSL_ADDR_LSB	0x0608
#define REG_ATR_PCIE_WIN0_T0_TRSL_ADDR_MSB	0x060C
#define REG_ATR_PCIE_WIN0_T0_TRSL_PARAM		0x0610
#define REG_PCIE_DEBUG_DUMMY_7			0x0D1C
#define REG_MSIX_ISTATUS_HOST_GRP0_0		0x0F00
#define REG_IMASK_HOST_MSIX_SET_GRP0_0		0x3000
#define REG_IMASK_HOST_MSIX_CLR_GRP0_0		0x3080
#define REG_IMASK_HOST_MSIX_GRP0_0		0x3100

/* mhccif registers */
#define MHCCIF_RC2EP_SW_BSY			0x4
#define MHCCIF_RC2EP_SW_TCHNUM			0xC
#define MHCCIF_RC2EP_EVT_DEVICE_RESET		BIT(13)

#define MHCCIF_EP2RC_SW_INT_STS			0x10
#define MHCCIF_EP2RC_SW_INT_ACK			0x14
#define MHCCIF_EP2RC_SW_INT_EAP_MASK		0x20
#define MHCCIF_EP2RC_SW_INT_EAP_MASK_SET	0x30
#define MHCCIF_EP2RC_SW_INT_EAP_MASK_CLR	0x40
#define MHCCIF_EP2RC_EVT_BOOT_FLOW_SYNC		BIT(5)
#define MHCCIF_EP2RC_EVT_ASYNC_HS_NOTIFY_SAP	BIT(15)
#define MHCCIF_EP2RC_EVT_ASYNC_HS_NOTIFY_MD	BIT(16)

#endif /* __MTK_PCI_REG_H__ */
