/* SPDX-License-Identifier: GPL-2.0-only
 *
 * Copyright (c) 2022, MediaTek Inc.
 */

#ifndef __MTK_PCI_REG_H__
#define __MTK_PCI_REG_H__

#define REG_PCIE_MISC_CTRL			0x0348
#define REG_ATR_PCIE_WIN0_T0_SRC_ADDR_LSB	0x0600
#define REG_ATR_PCIE_WIN0_T0_SRC_ADDR_MSB	0x0604
#define REG_ATR_PCIE_WIN0_T0_TRSL_ADDR_LSB	0x0608
#define REG_ATR_PCIE_WIN0_T0_TRSL_ADDR_MSB	0x060C
#define REG_ATR_PCIE_WIN0_T0_TRSL_PARAM		0x0610
#define REG_PCIE_DEBUG_DUMMY_3			0x0D0C
#define REG_PCIE_DEBUG_DUMMY_4			0x0D10
#define REG_PCIE_DEBUG_DUMMY_7			0x0D1C
#define REG_MSIX_ISTATUS_HOST_GRP0_0		0x0F00
#define REG_IMASK_HOST_MSIX_SET_GRP0_0		0x3000
#define REG_IMASK_HOST_MSIX_CLR_GRP0_0		0x3080
#define REG_IMASK_HOST_MSIX_GRP0_0		0x3100
#define REG_DEV_INFRA_BASE			0x10001000

/* mhccif registers */
#define MHCCIF_RC2EP_SW_BSY			0x4
#define MHCCIF_RC2EP_SW_TCHNUM			0xC
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_CLDMA0	BIT(4)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_CLDMA1	BIT(5)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_CLDMA3	BIT(6)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_CLDMA2	BIT(7)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_DPMAIF	BIT(8)
#define MHCCIF_RC2EP_EVT_PCIE_PM_SUSPEND_REQ	BIT(9)
#define MHCCIF_RC2EP_EVT_PCIE_PM_RESUME_REQ	BIT(10)
#define MHCCIF_RC2EP_EVT_PCIE_PM_SUSPEND_REQ_AP	BIT(11)
#define MHCCIF_RC2EP_EVT_PCIE_PM_RESUME_REQ_AP	BIT(12)
#define MHCCIF_RC2EP_EVT_DEVICE_RESET		BIT(13)
#define MHCCIF_RC2EP_EVT_RESERVED_FOR_TEST	BIT(31)

#define MHCCIF_EP2RC_SW_INT_STS			0x10
#define MHCCIF_EP2RC_SW_INT_ACK			0x14
#define MHCCIF_EP2RC_SW_INT_EAP_MASK		0x20
#define MHCCIF_EP2RC_SW_INT_EAP_MASK_SET	0x30
#define MHCCIF_EP2RC_SW_INT_EAP_MASK_CLR	0x40
#define MHCCIF_EP2RC_SPARE_REG_1		0x0104
#define MHCCIF_EP2RC_SPARE_REG_5		0x0114
#define MHCCIF_EP2RC_SPARE_REG_13		0x0134
#define MHCCIF_EP2RC_SPARE_REG_14		0x0138
#define MHCCIF_EP2RC_EVT_BOOT_FLOW_SYNC		BIT(5)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_CLDMA0	BIT(6)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_CLDMA1	BIT(7)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_CLDMA3	BIT(8)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_CLDMA2	BIT(9)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_DPMAIF	BIT(10)
#define MHCCIF_EP2RC_EVT_PCIE_PM_SUSPEND_ACK	BIT(11)
#define MHCCIF_EP2RC_EVT_PCIE_PM_RESUME_ACK	BIT(12)
#define MHCCIF_EP2RC_EVT_PCIE_PM_SUSPEND_ACK_AP	BIT(13)
#define MHCCIF_EP2RC_EVT_PCIE_PM_RESUME_ACK_AP	BIT(14)
#define MHCCIF_EP2RC_EVT_ASYNC_HS_NOTIFY_SAP	BIT(15)
#define MHCCIF_EP2RC_EVT_ASYNC_HS_NOTIFY_MD	BIT(16)
#define MHCCIF_EP2RC_EVT_SOFT_OFF_NOTIFY	BIT(17)
#define MHCCIF_EP2RC_EVT_MD_REBOOT		BIT(19)
#define MHCCIF_EP2RC_EVT_MD_POWEROFF		BIT(20)
#define MHCCIF_EP2RC_EVT_GNSS_ENABLE		BIT(21)
#define MHCCIF_EP2RC_EVT_GNSS_DISABLE		BIT(22)
#define MHCCIF_EP2RC_EVT_FRC_DONE_NOTIFY	BIT(24)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_TEST1	BIT(30)
#define MHCCIF_EP2RC_EVT_RESERVED_FOR_TEST2	BIT(31)

#endif /* __MTK_PCI_REG_H__ */
