# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 2020 Intel Corporation.

TEST_PROGS := TEST_PREREQUISITES.sh \
	TEST_XSK.sh
TEST_FILES := prereqs.sh xskenv.sh
TEST_TRANSIENT_FILES := veth.spec

KSFT_KHDR_INSTALL := 1
include ../lib.mk
