/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/netdev.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_NETDEV_H
#define _UAPI_LINUX_NETDEV_H

#define NETDEV_FAMILY_NAME	"netdev"
#define NETDEV_FAMILY_VERSION	1

enum netdev_xdp_act {
	NETDEV_XDP_ACT_ABORTED_BIT,
	NETDEV_XDP_ACT_DROP_BIT,
	NETDEV_XDP_ACT_PASS_BIT,
	NETDEV_XDP_ACT_TX_BIT,
	NETDEV_XDP_ACT_REDIRECT_BIT,
	NETDEV_XDP_ACT_NDO_XMIT_BIT,
	NETDEV_XDP_ACT_XSK_ZEROCOPY_BIT,
	NETDEV_XDP_ACT_HW_OFFLOAD_BIT,
	NETDEV_XDP_ACT_RX_SG_BIT,
	NETDEV_XDP_ACT_NDO_XMIT_SG_BIT
};

#define NETDEV_XDP_ACT_ABORTED		BIT(NETDEV_XDP_ACT_ABORTED_BIT)
#define NETDEV_XDP_ACT_DROP		BIT(NETDEV_XDP_ACT_DROP_BIT)
#define NETDEV_XDP_ACT_PASS		BIT(NETDEV_XDP_ACT_PASS_BIT)
#define NETDEV_XDP_ACT_TX		BIT(NETDEV_XDP_ACT_TX_BIT)
#define NETDEV_XDP_ACT_REDIRECT		BIT(NETDEV_XDP_ACT_REDIRECT_BIT)
#define NETDEV_XDP_ACT_NDO_XMIT		BIT(NETDEV_XDP_ACT_NDO_XMIT_BIT)
#define NETDEV_XDP_ACT_XSK_ZEROCOPY	BIT(NETDEV_XDP_ACT_XSK_ZEROCOPY_BIT)
#define NETDEV_XDP_ACT_HW_OFFLOAD	BIT(NETDEV_XDP_ACT_HW_OFFLOAD_BIT)
#define NETDEV_XDP_ACT_RX_SG		BIT(NETDEV_XDP_ACT_RX_SG_BIT)
#define NETDEV_XDP_ACT_NDO_XMIT_SG	BIT(NETDEV_XDP_ACT_NDO_XMIT_SG_BIT)

#define NETDEV_XDP_ACT_BASIC		(NETDEV_XDP_ACT_DROP |	\
					 NETDEV_XDP_ACT_PASS |	\
					 NETDEV_XDP_ACT_TX |	\
					 NETDEV_XDP_ACT_ABORTED)
#define NETDEV_XDP_ACT_FULL		(NETDEV_XDP_ACT_BASIC |	\
					 NETDEV_XDP_ACT_REDIRECT)
#define NETDEV_XDP_ACT_ZC		(NETDEV_XDP_ACT_FULL |	\
					 NETDEV_XDP_ACT_XSK_ZEROCOPY)

enum {
	NETDEV_A_DEV_IFINDEX = 1,
	NETDEV_A_DEV_PAD,
	NETDEV_A_DEV_XDP_FEATURES,

	__NETDEV_A_DEV_MAX,
	NETDEV_A_DEV_MAX = (__NETDEV_A_DEV_MAX - 1)
};

enum {
	NETDEV_CMD_DEV_GET = 1,
	NETDEV_CMD_DEV_ADD_NTF,
	NETDEV_CMD_DEV_DEL_NTF,
	NETDEV_CMD_DEV_CHANGE_NTF,

	__NETDEV_CMD_MAX,
	NETDEV_CMD_MAX = (__NETDEV_CMD_MAX - 1)
};

#define NETDEV_MCGRP_MGMT	"mgmt"

#endif /* _UAPI_LINUX_NETDEV_H */
