# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2026 Nebula Matrix Limited.

obj-$(CONFIG_NBL) := nbl.o

nbl-objs +=	nbl_common/nbl_common.o \
		nbl_channel/nbl_channel.o \
		nbl_hw/nbl_hw_leonis/nbl_hw_leonis.o \
		nbl_hw/nbl_hw_leonis/nbl_resource_leonis.o \
		nbl_hw/nbl_resource.o \
		nbl_hw/nbl_interrupt.o \
		nbl_hw/nbl_chip.o \
		nbl_core/nbl_dispatch.o \
		nbl_main.o
