#define __INVALID_ATOMIC_ACCESS_TEST(op, reg)				\
	{								\
		"atomic " #op " access through non-pointer ",		\
		.insns = {						\
			BPF_MOV64_IMM(BPF_REG_0, 1),			\
			BPF_MOV64_IMM(BPF_REG_1, 0),			\
			BPF_ATOMIC_OP(BPF_DW, op, BPF_REG_1, BPF_REG_0, -8), \
			BPF_MOV64_IMM(BPF_REG_0, 0),			\
			BPF_EXIT_INSN(),				\
		},							\
		.result = REJECT,					\
		.errstr = #reg " invalid mem access 'scalar'"		\
	}
__INVALID_ATOMIC_ACCESS_TEST(BPF_ADD, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_ADD | BPF_FETCH, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_AND, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_AND | BPF_FETCH, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_OR, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_OR | BPF_FETCH, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_XOR, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_XOR | BPF_FETCH, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_XCHG, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_CMPXCHG, R1),
__INVALID_ATOMIC_ACCESS_TEST(BPF_LOAD_ACQ, R0),
__INVALID_ATOMIC_ACCESS_TEST(BPF_STORE_REL, R1),