{
  "atomic_fetch_or: precision marking test",
  .insns = {
	BPF_CALL_REL(1),
    BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_1, 1000),
    BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
    BPF_STX_MEM(BPF_DW, BPF_REG_3, BPF_REG_1, -120),
    BPF_MOV64_REG(BPF_REG_7, BPF_REG_10),
    BPF_ATOMIC_OP(BPF_W, BPF_OR | BPF_FETCH, BPF_REG_10, BPF_REG_7, -120),
    BPF_ALU32_REG(BPF_OR, BPF_REG_7, BPF_REG_3),
	BPF_MOV64_IMM(BPF_REG_0, 0),
    BPF_EXIT_INSN(),
  },
  .result  = REJECT,
  .errstr = "R7 32-bit pointer arithmetic prohibited",
  .result_unpriv = REJECT,
  .errstr_unpriv = "loading/calling other bpf or kernel functions are allowed for CAP_BPF and CAP_SYS_ADMIN",
},
