{
       "dynptr: rewrite dynptr slot (pruning)",
        .insns = {
        BPF_MOV64_IMM(BPF_REG_0, 0),
        BPF_LD_MAP_FD(BPF_REG_6, 0),
        BPF_MOV64_REG(BPF_REG_1, BPF_REG_6),
        BPF_MOV64_IMM(BPF_REG_2, 8),
        BPF_MOV64_IMM(BPF_REG_3, 0),
        BPF_MOV64_REG(BPF_REG_4, BPF_REG_10),
        BPF_ALU64_IMM(BPF_ADD, BPF_REG_4, -16),
        BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_reserve_dynptr),
        BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 0, 1),
        BPF_JMP_IMM(BPF_JA, 0, 0, 1),
        BPF_ST_MEM(BPF_DW, BPF_REG_10, -16, 0xeB9F),
        BPF_MOV64_REG(BPF_REG_1, BPF_REG_10),
        BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, -16),
        BPF_MOV64_IMM(BPF_REG_2, 0),
        BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_discard_dynptr),
        BPF_MOV64_IMM(BPF_REG_0, 0),
        BPF_EXIT_INSN(),
        },
	.fixup_map_ringbuf = { 1 },
	.result_unpriv = REJECT,
	.errstr_unpriv = "unknown func bpf_ringbuf_reserve_dynptr#198",
	.result = REJECT,
	.errstr = "arg 1 is an unacquired reference",
},
{
       "dynptr: type confusion (pruning)",
       .insns = {
       BPF_MOV64_IMM(BPF_REG_0, 0),
       BPF_LD_MAP_FD(BPF_REG_6, 0),
       BPF_LD_MAP_FD(BPF_REG_7, 0),
       BPF_MOV64_REG(BPF_REG_1, BPF_REG_6),
       BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
       BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -8),
       BPF_ST_MEM(BPF_DW, BPF_REG_2, 0, 0),
       BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
       BPF_ALU64_IMM(BPF_ADD, BPF_REG_3, -24),
       BPF_ST_MEM(BPF_DW, BPF_REG_10, -16, 0xeB9FeB9F),
       BPF_ST_MEM(BPF_DW, BPF_REG_10, -24, 0xeB9FeB9F),
       BPF_MOV64_IMM(BPF_REG_4, 0),
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_2),
       BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_map_update_elem),
       BPF_MOV64_REG(BPF_REG_1, BPF_REG_6),
       BPF_MOV64_REG(BPF_REG_2, BPF_REG_8),
       BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_map_lookup_elem),
       BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
       BPF_EXIT_INSN(),
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_0),
       BPF_MOV64_REG(BPF_REG_1, BPF_REG_7),
       BPF_MOV64_IMM(BPF_REG_2, 8),
       BPF_MOV64_IMM(BPF_REG_3, 0),
       BPF_MOV64_REG(BPF_REG_4, BPF_REG_10),
       BPF_ALU64_IMM(BPF_ADD, BPF_REG_4, -16),
       BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_0, 0),
       BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_reserve_dynptr),
       BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 0, 8),
       /* pad with insns to trigger add_new_state heuristic for straight line path */
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_8),
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_8),
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_8),
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_8),
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_8),
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_8),
       BPF_MOV64_REG(BPF_REG_8, BPF_REG_8),
       BPF_JMP_IMM(BPF_JA, 0, 0, 9),
       BPF_ST_MEM(BPF_DW, BPF_REG_10, -8, 0),
       BPF_ST_MEM(BPF_DW, BPF_REG_10, -16, 0),
       BPF_MOV64_REG(BPF_REG_1, BPF_REG_8),
       BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, 8),
       BPF_MOV64_IMM(BPF_REG_2, 0),
       BPF_MOV64_IMM(BPF_REG_3, 0),
       BPF_MOV64_REG(BPF_REG_4, BPF_REG_10),
       BPF_ALU64_IMM(BPF_ADD, BPF_REG_4, -16),
       BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_dynptr_from_mem),
       BPF_MOV64_REG(BPF_REG_1, BPF_REG_10),
       BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, -16),
       BPF_MOV64_IMM(BPF_REG_2, 0),
       BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_discard_dynptr),
       BPF_MOV64_IMM(BPF_REG_0, 0),
       BPF_EXIT_INSN(),
       },
       .fixup_map_hash_16b = { 1 },
       .fixup_map_ringbuf = { 3 },
       .result_unpriv = REJECT,
       .errstr_unpriv = "unknown func bpf_ringbuf_reserve_dynptr#198",
       .result = REJECT,
       .errstr = "arg 1 is an unacquired reference",
},
{
       "dynptr: rewrite dynptr slot (var_off)",
	.insns = {
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 16),
	BPF_LDX_MEM(BPF_W, BPF_REG_8, BPF_REG_10, -4),
	BPF_JMP_IMM(BPF_JGE, BPF_REG_8, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_JMP_IMM(BPF_JLE, BPF_REG_8, 16, 2),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	BPF_ALU64_IMM(BPF_AND, BPF_REG_8, 16),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_MOV64_IMM(BPF_REG_2, 8),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_MOV64_REG(BPF_REG_4, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_4, -32),
	BPF_ALU64_REG(BPF_ADD, BPF_REG_4, BPF_REG_8),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_reserve_dynptr),
	BPF_ST_MEM(BPF_DW, BPF_REG_10, -16, 0xeB9F),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, -32),
	BPF_ALU64_REG(BPF_ADD, BPF_REG_1, BPF_REG_8),
	BPF_MOV64_IMM(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_discard_dynptr),
	BPF_MOV64_REG(BPF_REG_0, BPF_REG_8),
	BPF_EXIT_INSN(),
	},
	.fixup_map_ringbuf = { 9 },
	.result_unpriv = REJECT,
	.errstr_unpriv = "R4 variable stack access prohibited for !root, var_off=(0x0; 0x10) off=-32",
	.result = REJECT,
	.errstr = "dynptr has to be at the constant offset",
},
{
       "dynptr: partial dynptr slot invalidate",
	.insns = {
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_LD_MAP_FD(BPF_REG_6, 0),
	BPF_LD_MAP_FD(BPF_REG_7, 0),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_7),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -8),
	BPF_ST_MEM(BPF_DW, BPF_REG_2, 0, 0),
	BPF_MOV64_REG(BPF_REG_3, BPF_REG_2),
	BPF_MOV64_IMM(BPF_REG_4, 0),
	BPF_MOV64_REG(BPF_REG_8, BPF_REG_2),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_map_update_elem),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_7),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_8),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_map_lookup_elem),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_REG(BPF_REG_7, BPF_REG_0),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_6),
	BPF_MOV64_IMM(BPF_REG_2, 8),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_MOV64_REG(BPF_REG_4, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_4, -24),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_reserve_dynptr),
	BPF_ST_MEM(BPF_DW, BPF_REG_10, -16, 0),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_7),
	BPF_MOV64_IMM(BPF_REG_2, 8),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_MOV64_REG(BPF_REG_4, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_4, -16),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_dynptr_from_mem),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, -512),
	BPF_MOV64_IMM(BPF_REG_2, 488),
	BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_3, -24),
	BPF_MOV64_IMM(BPF_REG_4, 0),
	BPF_MOV64_IMM(BPF_REG_5, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_dynptr_read),
	BPF_MOV64_IMM(BPF_REG_8, 1),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_MOV64_IMM(BPF_REG_8, 0),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, -24),
	BPF_MOV64_IMM(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_discard_dynptr),
	BPF_MOV64_REG(BPF_REG_0, BPF_REG_8),
	BPF_EXIT_INSN(),
	},
	.fixup_map_ringbuf = { 1 },
	.fixup_map_hash_8b = { 3 },
	.result_unpriv = REJECT,
	.errstr_unpriv = "unknown func bpf_ringbuf_reserve_dynptr#198",
	.result = REJECT,
	.errstr = "Expected an initialized dynptr as arg #3",
},
