{
	"map tracing: full stack is accepted",
	.insns = {
		BPF_ST_MEM(BPF_DW, BPF_REG_10, -512, 0),
		BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
		BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -512),
		BPF_LD_MAP_FD(BPF_REG_1, 0),
		BPF_MOV64_REG(BPF_REG_3, BPF_REG_2),
		BPF_MOV64_IMM(BPF_REG_4, 0),
		BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0,
			     BPF_FUNC_map_update_elem),
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.fixup_map_hash_8b = { 3 },
	.result_unpriv = ACCEPT,
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
},
{
	"map tracing: overfull stack is not accepted",
	.insns = {
		BPF_ST_MEM(BPF_DW, BPF_REG_10, -520, 0),
		BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
		BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -520),
		BPF_LD_MAP_FD(BPF_REG_1, 0),
		BPF_MOV64_REG(BPF_REG_3, BPF_REG_2),
		BPF_MOV64_IMM(BPF_REG_4, 0),
		BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0,
			     BPF_FUNC_map_update_elem),
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.fixup_map_hash_8b = { 3 },
	.result_unpriv = REJECT,
	.result = REJECT,
	.errstr = "invalid write to stack R10 off=-520 size=8",
	.errstr_unpriv = "invalid write to stack R10 off=-520 size=8",
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
},
