# SPDX-License-Identifier: GPL-2.0-only

STOP_ERROR :=

LIBTRACEEVENT_MIN_VERSION = 1.5
LIBTRACEFS_MIN_VERSION = 1.3

define lib_setup
  $(eval LIB_INCLUDES += $(shell sh -c "$(PKG_CONFIG) --cflags lib$(1)"))
  $(eval LDFLAGS += $(shell sh -c "$(PKG_CONFIG) --libs-only-L lib$(1)"))
  $(eval EXTLIBS += $(shell sh -c "$(PKG_CONFIG) --libs-only-l lib$(1)"))
endef

$(call feature_check,libtraceevent)
ifeq ($(feature-libtraceevent), 1)
  $(call detected,CONFIG_LIBTRACEEVENT)

  TEST = $(shell sh -c "$(PKG_CONFIG) --atleast-version $(LIBTRACEEVENT_MIN_VERSION) libtraceevent > /dev/null 2>&1 && echo y || echo n")
  ifeq ($(TEST),n)
    $(info libtraceevent version is too low, it must be at least $(LIBTRACEEVENT_MIN_VERSION))
    STOP_ERROR := 1
  endif

  $(call lib_setup,traceevent)
else
  STOP_ERROR := 1
  $(info libtraceevent is missing. Please install libtraceevent-dev/libtraceevent-devel)
endif

$(call feature_check,libtracefs)
ifeq ($(feature-libtracefs), 1)
  $(call detected,CONFIG_LIBTRACEFS)

  TEST = $(shell sh -c "$(PKG_CONFIG) --atleast-version $(LIBTRACEFS_MIN_VERSION) libtracefs > /dev/null 2>&1 && echo y || echo n")
  ifeq ($(TEST),n)
    $(info libtracefs version is too low, it must be at least $(LIBTRACEFS_MIN_VERSION))
    STOP_ERROR := 1
  endif

  $(call lib_setup,tracefs)
else
  STOP_ERROR := 1
  $(info libtracefs is missing. Please install libtracefs-dev/libtracefs-devel)
endif

ifndef BUILD_BPF
  # BPF monitors are optional but enabled by default
  BUILD_BPF := 1
endif

ifeq ($(BUILD_BPF),0)
  $(info BPF monitor support disabled, building without BPF monitor support.)
endif

$(call feature_check,libbpf)
ifeq ($(feature-libbpf), 1)
  $(call detected,CONFIG_LIBBPF)
else
  $(info libbpf is missing, building without BPF monitor support.)
  $(info Please install libbpf-dev/libbpf-devel)
  BUILD_BPF := 0
endif

ifeq ($(BUILD_BPF),1)
  CFLAGS += -DHAVE_LIBBPF
  $(call lib_setup,bpf)
endif

# Building BPF monitors requires clang and bpftool, RV with BPF monitors
# support can still run without building monitors
ifndef BUILD_BPF_OBJS
  BUILD_BPF_OBJS := $(BUILD_BPF)
endif

ifeq ($(BUILD_BPF_OBJS),1)
  $(call feature_check,clang-bpf-co-re)
  ifeq ($(feature-clang-bpf-co-re), 1)
    $(call detected,CONFIG_CLANG_BPF_CO_RE)
  else
    $(info clang is missing or does not support BPF CO-RE, cannot build BPF monitors.)
    $(info Please install clang)
    BUILD_BPF_OBJS := 0
  endif

  $(call feature_check,bpftool-btf)
  ifeq ($(feature-bpftool-btf), 1)
    $(call detected,CONFIG_BPFTOOL_BTF)
  else
    $(info bpftool is missing or does not support btf, cannot build BPF monitors.)
    $(info Please install bpftool)
    BUILD_BPF_OBJS := 0
  endif
endif

ifeq ($(STOP_ERROR),1)
  $(error Please, check the errors above.)
endif
