/*
 * Copyright 2026 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _vpe_3_0_0_OFFSET_HEADER
#define _vpe_3_0_0_OFFSET_HEADER


// addressBlock: vpe_vpec_vpecdec
// base address: 0x46000
#define regVPEC_UCODE_ADDR                                                                              0x0001
#define regVPEC_UCODE_ADDR_BASE_IDX                                                                     0
#define regVPEC_UCODE_DATA                                                                              0x0002
#define regVPEC_UCODE_DATA_BASE_IDX                                                                     0
#define regVPEC_F32_CNTL                                                                                0x0003
#define regVPEC_F32_CNTL_BASE_IDX                                                                       0
#define regVPEC_CNTL                                                                                    0x0016
#define regVPEC_CNTL_BASE_IDX                                                                           0
#define regVPEC_CNTL_DCC                                                                                0x0017
#define regVPEC_CNTL_DCC_BASE_IDX                                                                       0
#define regVPEC_CNTL1                                                                                   0x0019
#define regVPEC_CNTL1_BASE_IDX                                                                          0
#define regVPEC_CNTL2                                                                                   0x001a
#define regVPEC_CNTL2_BASE_IDX                                                                          0
#define regVPEC_QUEUE_RESET_REQ                                                                         0x0033
#define regVPEC_QUEUE_RESET_REQ_BASE_IDX                                                                0
#define regVPEC_PUB_DUMMY0                                                                              0x0052
#define regVPEC_PUB_DUMMY0_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY1                                                                              0x0053
#define regVPEC_PUB_DUMMY1_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY2                                                                              0x0054
#define regVPEC_PUB_DUMMY2_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY3                                                                              0x0055
#define regVPEC_PUB_DUMMY3_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY4                                                                              0x0056
#define regVPEC_PUB_DUMMY4_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY5                                                                              0x0057
#define regVPEC_PUB_DUMMY5_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY6                                                                              0x0058
#define regVPEC_PUB_DUMMY6_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY7                                                                              0x0059
#define regVPEC_PUB_DUMMY7_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY8                                                                              0x005a
#define regVPEC_PUB_DUMMY8_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY9                                                                              0x005b
#define regVPEC_PUB_DUMMY9_BASE_IDX                                                                     0
#define regVPEC_PUB_DUMMY10                                                                             0x005c
#define regVPEC_PUB_DUMMY10_BASE_IDX                                                                    0
#define regVPEC_PUB_DUMMY11                                                                             0x005d
#define regVPEC_PUB_DUMMY11_BASE_IDX                                                                    0
#define regVPEC_UCODE1_CHECKSUM                                                                         0x005e
#define regVPEC_UCODE1_CHECKSUM_BASE_IDX                                                                0
#define regVPEC_UCODE_CHECKSUM                                                                          0x0060
#define regVPEC_UCODE_CHECKSUM_BASE_IDX                                                                 0
#define regVPEC_STATUS                                                                                  0x006e
#define regVPEC_STATUS_BASE_IDX                                                                         0
#define regVPEC_STATUS1                                                                                 0x006f
#define regVPEC_STATUS1_BASE_IDX                                                                        0
#define regVPEC_STATUS2                                                                                 0x0070
#define regVPEC_STATUS2_BASE_IDX                                                                        0
#define regVPEC_STATUS3                                                                                 0x0071
#define regVPEC_STATUS3_BASE_IDX                                                                        0
#define regVPEC_STATUS4                                                                                 0x0072
#define regVPEC_STATUS4_BASE_IDX                                                                        0
#define regVPEC_STATUS5                                                                                 0x0073
#define regVPEC_STATUS5_BASE_IDX                                                                        0
#define regVPEC_STATUS6                                                                                 0x0074
#define regVPEC_STATUS6_BASE_IDX                                                                        0
#define regVPEC_STATUS7                                                                                 0x0075
#define regVPEC_STATUS7_BASE_IDX                                                                        0
#define regVPEC_STATUS8                                                                                 0x0076
#define regVPEC_STATUS8_BASE_IDX                                                                        0
#define regVPEC_STATUS9                                                                                 0x0077
#define regVPEC_STATUS9_BASE_IDX                                                                        0
#define regVPEC_STATUS10                                                                                0x0078
#define regVPEC_STATUS10_BASE_IDX                                                                       0
#define regVPEC_STATUS11                                                                                0x0079
#define regVPEC_STATUS11_BASE_IDX                                                                       0
#define regVPEC_STATUS12                                                                                0x007a
#define regVPEC_STATUS12_BASE_IDX                                                                       0
#define regVPEC_STATUS13                                                                                0x007b
#define regVPEC_STATUS13_BASE_IDX                                                                       0
#define regVPEC_QUEUE_STATUS0                                                                           0x007d
#define regVPEC_QUEUE_STATUS0_BASE_IDX                                                                  0
#define regVPEC_QUEUE_HANG_STATUS                                                                       0x007e
#define regVPEC_QUEUE_HANG_STATUS_BASE_IDX                                                              0
#define regVPEC_PG_CNTL                                                                                 0x00b8
#define regVPEC_PG_CNTL_BASE_IDX                                                                        0
#define regVPEC_QUEUE0_RB_CNTL                                                                          0x00c0
#define regVPEC_QUEUE0_RB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_SCHEDULE_CNTL                                                                    0x00c1
#define regVPEC_QUEUE0_SCHEDULE_CNTL_BASE_IDX                                                           0
#define regVPEC_QUEUE0_RB_BASE                                                                          0x00c2
#define regVPEC_QUEUE0_RB_BASE_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_RB_BASE_HI                                                                       0x00c3
#define regVPEC_QUEUE0_RB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE0_RB_RPTR                                                                          0x00c4
#define regVPEC_QUEUE0_RB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_RB_RPTR_HI                                                                       0x00c5
#define regVPEC_QUEUE0_RB_RPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE0_RB_WPTR                                                                          0x00c6
#define regVPEC_QUEUE0_RB_WPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_RB_WPTR_HI                                                                       0x00c7
#define regVPEC_QUEUE0_RB_WPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE0_RB_RPTR_ADDR_HI                                                                  0x00c8
#define regVPEC_QUEUE0_RB_RPTR_ADDR_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE0_RB_RPTR_ADDR_LO                                                                  0x00c9
#define regVPEC_QUEUE0_RB_RPTR_ADDR_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE0_RB_AQL_CNTL                                                                      0x00ca
#define regVPEC_QUEUE0_RB_AQL_CNTL_BASE_IDX                                                             0
#define regVPEC_QUEUE0_MINOR_PTR_UPDATE                                                                 0x00cb
#define regVPEC_QUEUE0_MINOR_PTR_UPDATE_BASE_IDX                                                        0
#define regVPEC_QUEUE0_CD_INFO                                                                          0x00cc
#define regVPEC_QUEUE0_CD_INFO_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_RB_PREEMPT                                                                       0x00cd
#define regVPEC_QUEUE0_RB_PREEMPT_BASE_IDX                                                              0
#define regVPEC_QUEUE0_SKIP_CNTL                                                                        0x00ce
#define regVPEC_QUEUE0_SKIP_CNTL_BASE_IDX                                                               0
#define regVPEC_QUEUE0_DOORBELL                                                                         0x00cf
#define regVPEC_QUEUE0_DOORBELL_BASE_IDX                                                                0
#define regVPEC_QUEUE0_DOORBELL_OFFSET                                                                  0x00d0
#define regVPEC_QUEUE0_DOORBELL_OFFSET_BASE_IDX                                                         0
#define regVPEC_QUEUE0_DUMMY0                                                                           0x00d1
#define regVPEC_QUEUE0_DUMMY0_BASE_IDX                                                                  0
#define regVPEC_QUEUE0_DUMMY1                                                                           0x00d2
#define regVPEC_QUEUE0_DUMMY1_BASE_IDX                                                                  0
#define regVPEC_QUEUE0_DUMMY2                                                                           0x00d3
#define regVPEC_QUEUE0_DUMMY2_BASE_IDX                                                                  0
#define regVPEC_QUEUE0_DUMMY3                                                                           0x00d4
#define regVPEC_QUEUE0_DUMMY3_BASE_IDX                                                                  0
#define regVPEC_QUEUE0_DUMMY4                                                                           0x00d5
#define regVPEC_QUEUE0_DUMMY4_BASE_IDX                                                                  0
#define regVPEC_QUEUE0_IB_CNTL                                                                          0x00ec
#define regVPEC_QUEUE0_IB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_IB_RPTR                                                                          0x00ed
#define regVPEC_QUEUE0_IB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_IB_OFFSET                                                                        0x00ee
#define regVPEC_QUEUE0_IB_OFFSET_BASE_IDX                                                               0
#define regVPEC_QUEUE0_IB_BASE_LO                                                                       0x00ef
#define regVPEC_QUEUE0_IB_BASE_LO_BASE_IDX                                                              0
#define regVPEC_QUEUE0_IB_BASE_HI                                                                       0x00f0
#define regVPEC_QUEUE0_IB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE0_IB_SIZE                                                                          0x00f1
#define regVPEC_QUEUE0_IB_SIZE_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_CMDIB_CNTL                                                                       0x00f2
#define regVPEC_QUEUE0_CMDIB_CNTL_BASE_IDX                                                              0
#define regVPEC_QUEUE0_CMDIB_RPTR                                                                       0x00f3
#define regVPEC_QUEUE0_CMDIB_RPTR_BASE_IDX                                                              0
#define regVPEC_QUEUE0_CMDIB_OFFSET                                                                     0x00f4
#define regVPEC_QUEUE0_CMDIB_OFFSET_BASE_IDX                                                            0
#define regVPEC_QUEUE0_CMDIB_BASE_LO                                                                    0x00f5
#define regVPEC_QUEUE0_CMDIB_BASE_LO_BASE_IDX                                                           0
#define regVPEC_QUEUE0_CMDIB_BASE_HI                                                                    0x00f6
#define regVPEC_QUEUE0_CMDIB_BASE_HI_BASE_IDX                                                           0
#define regVPEC_QUEUE0_CMDIB_SIZE                                                                       0x00f7
#define regVPEC_QUEUE0_CMDIB_SIZE_BASE_IDX                                                              0
#define regVPEC_QUEUE0_3DLUTIB_CNTL                                                                     0x00f8
#define regVPEC_QUEUE0_3DLUTIB_CNTL_BASE_IDX                                                            0
#define regVPEC_QUEUE0_3DLUTIB_RPTR                                                                     0x00f9
#define regVPEC_QUEUE0_3DLUTIB_RPTR_BASE_IDX                                                            0
#define regVPEC_QUEUE0_3DLUTIB_OFFSET                                                                   0x00fa
#define regVPEC_QUEUE0_3DLUTIB_OFFSET_BASE_IDX                                                          0
#define regVPEC_QUEUE0_3DLUTIB_BASE_LO                                                                  0x00fb
#define regVPEC_QUEUE0_3DLUTIB_BASE_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE0_3DLUTIB_BASE_HI                                                                  0x00fc
#define regVPEC_QUEUE0_3DLUTIB_BASE_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE0_3DLUTIB_SIZE                                                                     0x00fd
#define regVPEC_QUEUE0_3DLUTIB_SIZE_BASE_IDX                                                            0
#define regVPEC_QUEUE0_CSA_ADDR_LO                                                                      0x00fe
#define regVPEC_QUEUE0_CSA_ADDR_LO_BASE_IDX                                                             0
#define regVPEC_QUEUE0_CSA_ADDR_HI                                                                      0x00ff
#define regVPEC_QUEUE0_CSA_ADDR_HI_BASE_IDX                                                             0
#define regVPEC_QUEUE0_CONTEXT_STATUS                                                                   0x0100
#define regVPEC_QUEUE0_CONTEXT_STATUS_BASE_IDX                                                          0
#define regVPEC_QUEUE0_DOORBELL_LOG                                                                     0x0101
#define regVPEC_QUEUE0_DOORBELL_LOG_BASE_IDX                                                            0
#define regVPEC_QUEUE0_IB_SUB_REMAIN                                                                    0x0102
#define regVPEC_QUEUE0_IB_SUB_REMAIN_BASE_IDX                                                           0
#define regVPEC_QUEUE0_PREEMPT                                                                          0x0103
#define regVPEC_QUEUE0_PREEMPT_BASE_IDX                                                                 0
#define regVPEC_QUEUE0_LOG0BUFFER_CFG                                                                   0x0104
#define regVPEC_QUEUE0_LOG0BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE0_LOG1BUFFER_CFG                                                                   0x0105
#define regVPEC_QUEUE0_LOG1BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE1_RB_CNTL                                                                          0x0118
#define regVPEC_QUEUE1_RB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_SCHEDULE_CNTL                                                                    0x0119
#define regVPEC_QUEUE1_SCHEDULE_CNTL_BASE_IDX                                                           0
#define regVPEC_QUEUE1_RB_BASE                                                                          0x011a
#define regVPEC_QUEUE1_RB_BASE_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_RB_BASE_HI                                                                       0x011b
#define regVPEC_QUEUE1_RB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE1_RB_RPTR                                                                          0x011c
#define regVPEC_QUEUE1_RB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_RB_RPTR_HI                                                                       0x011d
#define regVPEC_QUEUE1_RB_RPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE1_RB_WPTR                                                                          0x011e
#define regVPEC_QUEUE1_RB_WPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_RB_WPTR_HI                                                                       0x011f
#define regVPEC_QUEUE1_RB_WPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE1_RB_RPTR_ADDR_HI                                                                  0x0120
#define regVPEC_QUEUE1_RB_RPTR_ADDR_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE1_RB_RPTR_ADDR_LO                                                                  0x0121
#define regVPEC_QUEUE1_RB_RPTR_ADDR_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE1_RB_AQL_CNTL                                                                      0x0122
#define regVPEC_QUEUE1_RB_AQL_CNTL_BASE_IDX                                                             0
#define regVPEC_QUEUE1_MINOR_PTR_UPDATE                                                                 0x0123
#define regVPEC_QUEUE1_MINOR_PTR_UPDATE_BASE_IDX                                                        0
#define regVPEC_QUEUE1_CD_INFO                                                                          0x0124
#define regVPEC_QUEUE1_CD_INFO_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_RB_PREEMPT                                                                       0x0125
#define regVPEC_QUEUE1_RB_PREEMPT_BASE_IDX                                                              0
#define regVPEC_QUEUE1_SKIP_CNTL                                                                        0x0126
#define regVPEC_QUEUE1_SKIP_CNTL_BASE_IDX                                                               0
#define regVPEC_QUEUE1_DOORBELL                                                                         0x0127
#define regVPEC_QUEUE1_DOORBELL_BASE_IDX                                                                0
#define regVPEC_QUEUE1_DOORBELL_OFFSET                                                                  0x0128
#define regVPEC_QUEUE1_DOORBELL_OFFSET_BASE_IDX                                                         0
#define regVPEC_QUEUE1_DUMMY0                                                                           0x0129
#define regVPEC_QUEUE1_DUMMY0_BASE_IDX                                                                  0
#define regVPEC_QUEUE1_DUMMY1                                                                           0x012a
#define regVPEC_QUEUE1_DUMMY1_BASE_IDX                                                                  0
#define regVPEC_QUEUE1_DUMMY2                                                                           0x012b
#define regVPEC_QUEUE1_DUMMY2_BASE_IDX                                                                  0
#define regVPEC_QUEUE1_DUMMY3                                                                           0x012c
#define regVPEC_QUEUE1_DUMMY3_BASE_IDX                                                                  0
#define regVPEC_QUEUE1_DUMMY4                                                                           0x012d
#define regVPEC_QUEUE1_DUMMY4_BASE_IDX                                                                  0
#define regVPEC_QUEUE1_IB_CNTL                                                                          0x0144
#define regVPEC_QUEUE1_IB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_IB_RPTR                                                                          0x0145
#define regVPEC_QUEUE1_IB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_IB_OFFSET                                                                        0x0146
#define regVPEC_QUEUE1_IB_OFFSET_BASE_IDX                                                               0
#define regVPEC_QUEUE1_IB_BASE_LO                                                                       0x0147
#define regVPEC_QUEUE1_IB_BASE_LO_BASE_IDX                                                              0
#define regVPEC_QUEUE1_IB_BASE_HI                                                                       0x0148
#define regVPEC_QUEUE1_IB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE1_IB_SIZE                                                                          0x0149
#define regVPEC_QUEUE1_IB_SIZE_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_CMDIB_CNTL                                                                       0x014a
#define regVPEC_QUEUE1_CMDIB_CNTL_BASE_IDX                                                              0
#define regVPEC_QUEUE1_CMDIB_RPTR                                                                       0x014b
#define regVPEC_QUEUE1_CMDIB_RPTR_BASE_IDX                                                              0
#define regVPEC_QUEUE1_CMDIB_OFFSET                                                                     0x014c
#define regVPEC_QUEUE1_CMDIB_OFFSET_BASE_IDX                                                            0
#define regVPEC_QUEUE1_CMDIB_BASE_LO                                                                    0x014d
#define regVPEC_QUEUE1_CMDIB_BASE_LO_BASE_IDX                                                           0
#define regVPEC_QUEUE1_CMDIB_BASE_HI                                                                    0x014e
#define regVPEC_QUEUE1_CMDIB_BASE_HI_BASE_IDX                                                           0
#define regVPEC_QUEUE1_CMDIB_SIZE                                                                       0x014f
#define regVPEC_QUEUE1_CMDIB_SIZE_BASE_IDX                                                              0
#define regVPEC_QUEUE1_3DLUTIB_CNTL                                                                     0x0150
#define regVPEC_QUEUE1_3DLUTIB_CNTL_BASE_IDX                                                            0
#define regVPEC_QUEUE1_3DLUTIB_RPTR                                                                     0x0151
#define regVPEC_QUEUE1_3DLUTIB_RPTR_BASE_IDX                                                            0
#define regVPEC_QUEUE1_3DLUTIB_OFFSET                                                                   0x0152
#define regVPEC_QUEUE1_3DLUTIB_OFFSET_BASE_IDX                                                          0
#define regVPEC_QUEUE1_3DLUTIB_BASE_LO                                                                  0x0153
#define regVPEC_QUEUE1_3DLUTIB_BASE_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE1_3DLUTIB_BASE_HI                                                                  0x0154
#define regVPEC_QUEUE1_3DLUTIB_BASE_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE1_3DLUTIB_SIZE                                                                     0x0155
#define regVPEC_QUEUE1_3DLUTIB_SIZE_BASE_IDX                                                            0
#define regVPEC_QUEUE1_CSA_ADDR_LO                                                                      0x0156
#define regVPEC_QUEUE1_CSA_ADDR_LO_BASE_IDX                                                             0
#define regVPEC_QUEUE1_CSA_ADDR_HI                                                                      0x0157
#define regVPEC_QUEUE1_CSA_ADDR_HI_BASE_IDX                                                             0
#define regVPEC_QUEUE1_CONTEXT_STATUS                                                                   0x0158
#define regVPEC_QUEUE1_CONTEXT_STATUS_BASE_IDX                                                          0
#define regVPEC_QUEUE1_DOORBELL_LOG                                                                     0x0159
#define regVPEC_QUEUE1_DOORBELL_LOG_BASE_IDX                                                            0
#define regVPEC_QUEUE1_IB_SUB_REMAIN                                                                    0x015a
#define regVPEC_QUEUE1_IB_SUB_REMAIN_BASE_IDX                                                           0
#define regVPEC_QUEUE1_PREEMPT                                                                          0x015b
#define regVPEC_QUEUE1_PREEMPT_BASE_IDX                                                                 0
#define regVPEC_QUEUE1_LOG0BUFFER_CFG                                                                   0x015c
#define regVPEC_QUEUE1_LOG0BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE1_LOG1BUFFER_CFG                                                                   0x015d
#define regVPEC_QUEUE1_LOG1BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE2_RB_CNTL                                                                          0x0170
#define regVPEC_QUEUE2_RB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_SCHEDULE_CNTL                                                                    0x0171
#define regVPEC_QUEUE2_SCHEDULE_CNTL_BASE_IDX                                                           0
#define regVPEC_QUEUE2_RB_BASE                                                                          0x0172
#define regVPEC_QUEUE2_RB_BASE_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_RB_BASE_HI                                                                       0x0173
#define regVPEC_QUEUE2_RB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE2_RB_RPTR                                                                          0x0174
#define regVPEC_QUEUE2_RB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_RB_RPTR_HI                                                                       0x0175
#define regVPEC_QUEUE2_RB_RPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE2_RB_WPTR                                                                          0x0176
#define regVPEC_QUEUE2_RB_WPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_RB_WPTR_HI                                                                       0x0177
#define regVPEC_QUEUE2_RB_WPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE2_RB_RPTR_ADDR_HI                                                                  0x0178
#define regVPEC_QUEUE2_RB_RPTR_ADDR_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE2_RB_RPTR_ADDR_LO                                                                  0x0179
#define regVPEC_QUEUE2_RB_RPTR_ADDR_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE2_RB_AQL_CNTL                                                                      0x017a
#define regVPEC_QUEUE2_RB_AQL_CNTL_BASE_IDX                                                             0
#define regVPEC_QUEUE2_MINOR_PTR_UPDATE                                                                 0x017b
#define regVPEC_QUEUE2_MINOR_PTR_UPDATE_BASE_IDX                                                        0
#define regVPEC_QUEUE2_CD_INFO                                                                          0x017c
#define regVPEC_QUEUE2_CD_INFO_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_RB_PREEMPT                                                                       0x017d
#define regVPEC_QUEUE2_RB_PREEMPT_BASE_IDX                                                              0
#define regVPEC_QUEUE2_SKIP_CNTL                                                                        0x017e
#define regVPEC_QUEUE2_SKIP_CNTL_BASE_IDX                                                               0
#define regVPEC_QUEUE2_DOORBELL                                                                         0x017f
#define regVPEC_QUEUE2_DOORBELL_BASE_IDX                                                                0
#define regVPEC_QUEUE2_DOORBELL_OFFSET                                                                  0x0180
#define regVPEC_QUEUE2_DOORBELL_OFFSET_BASE_IDX                                                         0
#define regVPEC_QUEUE2_DUMMY0                                                                           0x0181
#define regVPEC_QUEUE2_DUMMY0_BASE_IDX                                                                  0
#define regVPEC_QUEUE2_DUMMY1                                                                           0x0182
#define regVPEC_QUEUE2_DUMMY1_BASE_IDX                                                                  0
#define regVPEC_QUEUE2_DUMMY2                                                                           0x0183
#define regVPEC_QUEUE2_DUMMY2_BASE_IDX                                                                  0
#define regVPEC_QUEUE2_DUMMY3                                                                           0x0184
#define regVPEC_QUEUE2_DUMMY3_BASE_IDX                                                                  0
#define regVPEC_QUEUE2_DUMMY4                                                                           0x0185
#define regVPEC_QUEUE2_DUMMY4_BASE_IDX                                                                  0
#define regVPEC_QUEUE2_IB_CNTL                                                                          0x019c
#define regVPEC_QUEUE2_IB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_IB_RPTR                                                                          0x019d
#define regVPEC_QUEUE2_IB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_IB_OFFSET                                                                        0x019e
#define regVPEC_QUEUE2_IB_OFFSET_BASE_IDX                                                               0
#define regVPEC_QUEUE2_IB_BASE_LO                                                                       0x019f
#define regVPEC_QUEUE2_IB_BASE_LO_BASE_IDX                                                              0
#define regVPEC_QUEUE2_IB_BASE_HI                                                                       0x01a0
#define regVPEC_QUEUE2_IB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE2_IB_SIZE                                                                          0x01a1
#define regVPEC_QUEUE2_IB_SIZE_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_CMDIB_CNTL                                                                       0x01a2
#define regVPEC_QUEUE2_CMDIB_CNTL_BASE_IDX                                                              0
#define regVPEC_QUEUE2_CMDIB_RPTR                                                                       0x01a3
#define regVPEC_QUEUE2_CMDIB_RPTR_BASE_IDX                                                              0
#define regVPEC_QUEUE2_CMDIB_OFFSET                                                                     0x01a4
#define regVPEC_QUEUE2_CMDIB_OFFSET_BASE_IDX                                                            0
#define regVPEC_QUEUE2_CMDIB_BASE_LO                                                                    0x01a5
#define regVPEC_QUEUE2_CMDIB_BASE_LO_BASE_IDX                                                           0
#define regVPEC_QUEUE2_CMDIB_BASE_HI                                                                    0x01a6
#define regVPEC_QUEUE2_CMDIB_BASE_HI_BASE_IDX                                                           0
#define regVPEC_QUEUE2_CMDIB_SIZE                                                                       0x01a7
#define regVPEC_QUEUE2_CMDIB_SIZE_BASE_IDX                                                              0
#define regVPEC_QUEUE2_3DLUTIB_CNTL                                                                     0x01a8
#define regVPEC_QUEUE2_3DLUTIB_CNTL_BASE_IDX                                                            0
#define regVPEC_QUEUE2_3DLUTIB_RPTR                                                                     0x01a9
#define regVPEC_QUEUE2_3DLUTIB_RPTR_BASE_IDX                                                            0
#define regVPEC_QUEUE2_3DLUTIB_OFFSET                                                                   0x01aa
#define regVPEC_QUEUE2_3DLUTIB_OFFSET_BASE_IDX                                                          0
#define regVPEC_QUEUE2_3DLUTIB_BASE_LO                                                                  0x01ab
#define regVPEC_QUEUE2_3DLUTIB_BASE_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE2_3DLUTIB_BASE_HI                                                                  0x01ac
#define regVPEC_QUEUE2_3DLUTIB_BASE_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE2_3DLUTIB_SIZE                                                                     0x01ad
#define regVPEC_QUEUE2_3DLUTIB_SIZE_BASE_IDX                                                            0
#define regVPEC_QUEUE2_CSA_ADDR_LO                                                                      0x01ae
#define regVPEC_QUEUE2_CSA_ADDR_LO_BASE_IDX                                                             0
#define regVPEC_QUEUE2_CSA_ADDR_HI                                                                      0x01af
#define regVPEC_QUEUE2_CSA_ADDR_HI_BASE_IDX                                                             0
#define regVPEC_QUEUE2_CONTEXT_STATUS                                                                   0x01b0
#define regVPEC_QUEUE2_CONTEXT_STATUS_BASE_IDX                                                          0
#define regVPEC_QUEUE2_DOORBELL_LOG                                                                     0x01b1
#define regVPEC_QUEUE2_DOORBELL_LOG_BASE_IDX                                                            0
#define regVPEC_QUEUE2_IB_SUB_REMAIN                                                                    0x01b2
#define regVPEC_QUEUE2_IB_SUB_REMAIN_BASE_IDX                                                           0
#define regVPEC_QUEUE2_PREEMPT                                                                          0x01b3
#define regVPEC_QUEUE2_PREEMPT_BASE_IDX                                                                 0
#define regVPEC_QUEUE2_LOG0BUFFER_CFG                                                                   0x01b4
#define regVPEC_QUEUE2_LOG0BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE2_LOG1BUFFER_CFG                                                                   0x01b5
#define regVPEC_QUEUE2_LOG1BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE3_RB_CNTL                                                                          0x01c8
#define regVPEC_QUEUE3_RB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_SCHEDULE_CNTL                                                                    0x01c9
#define regVPEC_QUEUE3_SCHEDULE_CNTL_BASE_IDX                                                           0
#define regVPEC_QUEUE3_RB_BASE                                                                          0x01ca
#define regVPEC_QUEUE3_RB_BASE_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_RB_BASE_HI                                                                       0x01cb
#define regVPEC_QUEUE3_RB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE3_RB_RPTR                                                                          0x01cc
#define regVPEC_QUEUE3_RB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_RB_RPTR_HI                                                                       0x01cd
#define regVPEC_QUEUE3_RB_RPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE3_RB_WPTR                                                                          0x01ce
#define regVPEC_QUEUE3_RB_WPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_RB_WPTR_HI                                                                       0x01cf
#define regVPEC_QUEUE3_RB_WPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE3_RB_RPTR_ADDR_HI                                                                  0x01d0
#define regVPEC_QUEUE3_RB_RPTR_ADDR_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE3_RB_RPTR_ADDR_LO                                                                  0x01d1
#define regVPEC_QUEUE3_RB_RPTR_ADDR_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE3_RB_AQL_CNTL                                                                      0x01d2
#define regVPEC_QUEUE3_RB_AQL_CNTL_BASE_IDX                                                             0
#define regVPEC_QUEUE3_MINOR_PTR_UPDATE                                                                 0x01d3
#define regVPEC_QUEUE3_MINOR_PTR_UPDATE_BASE_IDX                                                        0
#define regVPEC_QUEUE3_CD_INFO                                                                          0x01d4
#define regVPEC_QUEUE3_CD_INFO_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_RB_PREEMPT                                                                       0x01d5
#define regVPEC_QUEUE3_RB_PREEMPT_BASE_IDX                                                              0
#define regVPEC_QUEUE3_SKIP_CNTL                                                                        0x01d6
#define regVPEC_QUEUE3_SKIP_CNTL_BASE_IDX                                                               0
#define regVPEC_QUEUE3_DOORBELL                                                                         0x01d7
#define regVPEC_QUEUE3_DOORBELL_BASE_IDX                                                                0
#define regVPEC_QUEUE3_DOORBELL_OFFSET                                                                  0x01d8
#define regVPEC_QUEUE3_DOORBELL_OFFSET_BASE_IDX                                                         0
#define regVPEC_QUEUE3_DUMMY0                                                                           0x01d9
#define regVPEC_QUEUE3_DUMMY0_BASE_IDX                                                                  0
#define regVPEC_QUEUE3_DUMMY1                                                                           0x01da
#define regVPEC_QUEUE3_DUMMY1_BASE_IDX                                                                  0
#define regVPEC_QUEUE3_DUMMY2                                                                           0x01db
#define regVPEC_QUEUE3_DUMMY2_BASE_IDX                                                                  0
#define regVPEC_QUEUE3_DUMMY3                                                                           0x01dc
#define regVPEC_QUEUE3_DUMMY3_BASE_IDX                                                                  0
#define regVPEC_QUEUE3_DUMMY4                                                                           0x01dd
#define regVPEC_QUEUE3_DUMMY4_BASE_IDX                                                                  0
#define regVPEC_QUEUE3_IB_CNTL                                                                          0x01f4
#define regVPEC_QUEUE3_IB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_IB_RPTR                                                                          0x01f5
#define regVPEC_QUEUE3_IB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_IB_OFFSET                                                                        0x01f6
#define regVPEC_QUEUE3_IB_OFFSET_BASE_IDX                                                               0
#define regVPEC_QUEUE3_IB_BASE_LO                                                                       0x01f7
#define regVPEC_QUEUE3_IB_BASE_LO_BASE_IDX                                                              0
#define regVPEC_QUEUE3_IB_BASE_HI                                                                       0x01f8
#define regVPEC_QUEUE3_IB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE3_IB_SIZE                                                                          0x01f9
#define regVPEC_QUEUE3_IB_SIZE_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_CMDIB_CNTL                                                                       0x01fa
#define regVPEC_QUEUE3_CMDIB_CNTL_BASE_IDX                                                              0
#define regVPEC_QUEUE3_CMDIB_RPTR                                                                       0x01fb
#define regVPEC_QUEUE3_CMDIB_RPTR_BASE_IDX                                                              0
#define regVPEC_QUEUE3_CMDIB_OFFSET                                                                     0x01fc
#define regVPEC_QUEUE3_CMDIB_OFFSET_BASE_IDX                                                            0
#define regVPEC_QUEUE3_CMDIB_BASE_LO                                                                    0x01fd
#define regVPEC_QUEUE3_CMDIB_BASE_LO_BASE_IDX                                                           0
#define regVPEC_QUEUE3_CMDIB_BASE_HI                                                                    0x01fe
#define regVPEC_QUEUE3_CMDIB_BASE_HI_BASE_IDX                                                           0
#define regVPEC_QUEUE3_CMDIB_SIZE                                                                       0x01ff
#define regVPEC_QUEUE3_CMDIB_SIZE_BASE_IDX                                                              0
#define regVPEC_QUEUE3_3DLUTIB_CNTL                                                                     0x0200
#define regVPEC_QUEUE3_3DLUTIB_CNTL_BASE_IDX                                                            0
#define regVPEC_QUEUE3_3DLUTIB_RPTR                                                                     0x0201
#define regVPEC_QUEUE3_3DLUTIB_RPTR_BASE_IDX                                                            0
#define regVPEC_QUEUE3_3DLUTIB_OFFSET                                                                   0x0202
#define regVPEC_QUEUE3_3DLUTIB_OFFSET_BASE_IDX                                                          0
#define regVPEC_QUEUE3_3DLUTIB_BASE_LO                                                                  0x0203
#define regVPEC_QUEUE3_3DLUTIB_BASE_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE3_3DLUTIB_BASE_HI                                                                  0x0204
#define regVPEC_QUEUE3_3DLUTIB_BASE_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE3_3DLUTIB_SIZE                                                                     0x0205
#define regVPEC_QUEUE3_3DLUTIB_SIZE_BASE_IDX                                                            0
#define regVPEC_QUEUE3_CSA_ADDR_LO                                                                      0x0206
#define regVPEC_QUEUE3_CSA_ADDR_LO_BASE_IDX                                                             0
#define regVPEC_QUEUE3_CSA_ADDR_HI                                                                      0x0207
#define regVPEC_QUEUE3_CSA_ADDR_HI_BASE_IDX                                                             0
#define regVPEC_QUEUE3_CONTEXT_STATUS                                                                   0x0208
#define regVPEC_QUEUE3_CONTEXT_STATUS_BASE_IDX                                                          0
#define regVPEC_QUEUE3_DOORBELL_LOG                                                                     0x0209
#define regVPEC_QUEUE3_DOORBELL_LOG_BASE_IDX                                                            0
#define regVPEC_QUEUE3_IB_SUB_REMAIN                                                                    0x020a
#define regVPEC_QUEUE3_IB_SUB_REMAIN_BASE_IDX                                                           0
#define regVPEC_QUEUE3_PREEMPT                                                                          0x020b
#define regVPEC_QUEUE3_PREEMPT_BASE_IDX                                                                 0
#define regVPEC_QUEUE3_LOG0BUFFER_CFG                                                                   0x020c
#define regVPEC_QUEUE3_LOG0BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE3_LOG1BUFFER_CFG                                                                   0x020d
#define regVPEC_QUEUE3_LOG1BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE4_RB_CNTL                                                                          0x0220
#define regVPEC_QUEUE4_RB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_SCHEDULE_CNTL                                                                    0x0221
#define regVPEC_QUEUE4_SCHEDULE_CNTL_BASE_IDX                                                           0
#define regVPEC_QUEUE4_RB_BASE                                                                          0x0222
#define regVPEC_QUEUE4_RB_BASE_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_RB_BASE_HI                                                                       0x0223
#define regVPEC_QUEUE4_RB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE4_RB_RPTR                                                                          0x0224
#define regVPEC_QUEUE4_RB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_RB_RPTR_HI                                                                       0x0225
#define regVPEC_QUEUE4_RB_RPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE4_RB_WPTR                                                                          0x0226
#define regVPEC_QUEUE4_RB_WPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_RB_WPTR_HI                                                                       0x0227
#define regVPEC_QUEUE4_RB_WPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE4_RB_RPTR_ADDR_HI                                                                  0x0228
#define regVPEC_QUEUE4_RB_RPTR_ADDR_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE4_RB_RPTR_ADDR_LO                                                                  0x0229
#define regVPEC_QUEUE4_RB_RPTR_ADDR_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE4_RB_AQL_CNTL                                                                      0x022a
#define regVPEC_QUEUE4_RB_AQL_CNTL_BASE_IDX                                                             0
#define regVPEC_QUEUE4_MINOR_PTR_UPDATE                                                                 0x022b
#define regVPEC_QUEUE4_MINOR_PTR_UPDATE_BASE_IDX                                                        0
#define regVPEC_QUEUE4_CD_INFO                                                                          0x022c
#define regVPEC_QUEUE4_CD_INFO_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_RB_PREEMPT                                                                       0x022d
#define regVPEC_QUEUE4_RB_PREEMPT_BASE_IDX                                                              0
#define regVPEC_QUEUE4_SKIP_CNTL                                                                        0x022e
#define regVPEC_QUEUE4_SKIP_CNTL_BASE_IDX                                                               0
#define regVPEC_QUEUE4_DOORBELL                                                                         0x022f
#define regVPEC_QUEUE4_DOORBELL_BASE_IDX                                                                0
#define regVPEC_QUEUE4_DOORBELL_OFFSET                                                                  0x0230
#define regVPEC_QUEUE4_DOORBELL_OFFSET_BASE_IDX                                                         0
#define regVPEC_QUEUE4_DUMMY0                                                                           0x0231
#define regVPEC_QUEUE4_DUMMY0_BASE_IDX                                                                  0
#define regVPEC_QUEUE4_DUMMY1                                                                           0x0232
#define regVPEC_QUEUE4_DUMMY1_BASE_IDX                                                                  0
#define regVPEC_QUEUE4_DUMMY2                                                                           0x0233
#define regVPEC_QUEUE4_DUMMY2_BASE_IDX                                                                  0
#define regVPEC_QUEUE4_DUMMY3                                                                           0x0234
#define regVPEC_QUEUE4_DUMMY3_BASE_IDX                                                                  0
#define regVPEC_QUEUE4_DUMMY4                                                                           0x0235
#define regVPEC_QUEUE4_DUMMY4_BASE_IDX                                                                  0
#define regVPEC_QUEUE4_IB_CNTL                                                                          0x024c
#define regVPEC_QUEUE4_IB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_IB_RPTR                                                                          0x024d
#define regVPEC_QUEUE4_IB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_IB_OFFSET                                                                        0x024e
#define regVPEC_QUEUE4_IB_OFFSET_BASE_IDX                                                               0
#define regVPEC_QUEUE4_IB_BASE_LO                                                                       0x024f
#define regVPEC_QUEUE4_IB_BASE_LO_BASE_IDX                                                              0
#define regVPEC_QUEUE4_IB_BASE_HI                                                                       0x0250
#define regVPEC_QUEUE4_IB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE4_IB_SIZE                                                                          0x0251
#define regVPEC_QUEUE4_IB_SIZE_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_CMDIB_CNTL                                                                       0x0252
#define regVPEC_QUEUE4_CMDIB_CNTL_BASE_IDX                                                              0
#define regVPEC_QUEUE4_CMDIB_RPTR                                                                       0x0253
#define regVPEC_QUEUE4_CMDIB_RPTR_BASE_IDX                                                              0
#define regVPEC_QUEUE4_CMDIB_OFFSET                                                                     0x0254
#define regVPEC_QUEUE4_CMDIB_OFFSET_BASE_IDX                                                            0
#define regVPEC_QUEUE4_CMDIB_BASE_LO                                                                    0x0255
#define regVPEC_QUEUE4_CMDIB_BASE_LO_BASE_IDX                                                           0
#define regVPEC_QUEUE4_CMDIB_BASE_HI                                                                    0x0256
#define regVPEC_QUEUE4_CMDIB_BASE_HI_BASE_IDX                                                           0
#define regVPEC_QUEUE4_CMDIB_SIZE                                                                       0x0257
#define regVPEC_QUEUE4_CMDIB_SIZE_BASE_IDX                                                              0
#define regVPEC_QUEUE4_3DLUTIB_CNTL                                                                     0x0258
#define regVPEC_QUEUE4_3DLUTIB_CNTL_BASE_IDX                                                            0
#define regVPEC_QUEUE4_3DLUTIB_RPTR                                                                     0x0259
#define regVPEC_QUEUE4_3DLUTIB_RPTR_BASE_IDX                                                            0
#define regVPEC_QUEUE4_3DLUTIB_OFFSET                                                                   0x025a
#define regVPEC_QUEUE4_3DLUTIB_OFFSET_BASE_IDX                                                          0
#define regVPEC_QUEUE4_3DLUTIB_BASE_LO                                                                  0x025b
#define regVPEC_QUEUE4_3DLUTIB_BASE_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE4_3DLUTIB_BASE_HI                                                                  0x025c
#define regVPEC_QUEUE4_3DLUTIB_BASE_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE4_3DLUTIB_SIZE                                                                     0x025d
#define regVPEC_QUEUE4_3DLUTIB_SIZE_BASE_IDX                                                            0
#define regVPEC_QUEUE4_CSA_ADDR_LO                                                                      0x025e
#define regVPEC_QUEUE4_CSA_ADDR_LO_BASE_IDX                                                             0
#define regVPEC_QUEUE4_CSA_ADDR_HI                                                                      0x025f
#define regVPEC_QUEUE4_CSA_ADDR_HI_BASE_IDX                                                             0
#define regVPEC_QUEUE4_CONTEXT_STATUS                                                                   0x0260
#define regVPEC_QUEUE4_CONTEXT_STATUS_BASE_IDX                                                          0
#define regVPEC_QUEUE4_DOORBELL_LOG                                                                     0x0261
#define regVPEC_QUEUE4_DOORBELL_LOG_BASE_IDX                                                            0
#define regVPEC_QUEUE4_IB_SUB_REMAIN                                                                    0x0262
#define regVPEC_QUEUE4_IB_SUB_REMAIN_BASE_IDX                                                           0
#define regVPEC_QUEUE4_PREEMPT                                                                          0x0263
#define regVPEC_QUEUE4_PREEMPT_BASE_IDX                                                                 0
#define regVPEC_QUEUE4_LOG0BUFFER_CFG                                                                   0x0264
#define regVPEC_QUEUE4_LOG0BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE4_LOG1BUFFER_CFG                                                                   0x0265
#define regVPEC_QUEUE4_LOG1BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE5_RB_CNTL                                                                          0x0278
#define regVPEC_QUEUE5_RB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_SCHEDULE_CNTL                                                                    0x0279
#define regVPEC_QUEUE5_SCHEDULE_CNTL_BASE_IDX                                                           0
#define regVPEC_QUEUE5_RB_BASE                                                                          0x027a
#define regVPEC_QUEUE5_RB_BASE_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_RB_BASE_HI                                                                       0x027b
#define regVPEC_QUEUE5_RB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE5_RB_RPTR                                                                          0x027c
#define regVPEC_QUEUE5_RB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_RB_RPTR_HI                                                                       0x027d
#define regVPEC_QUEUE5_RB_RPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE5_RB_WPTR                                                                          0x027e
#define regVPEC_QUEUE5_RB_WPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_RB_WPTR_HI                                                                       0x027f
#define regVPEC_QUEUE5_RB_WPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE5_RB_RPTR_ADDR_HI                                                                  0x0280
#define regVPEC_QUEUE5_RB_RPTR_ADDR_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE5_RB_RPTR_ADDR_LO                                                                  0x0281
#define regVPEC_QUEUE5_RB_RPTR_ADDR_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE5_RB_AQL_CNTL                                                                      0x0282
#define regVPEC_QUEUE5_RB_AQL_CNTL_BASE_IDX                                                             0
#define regVPEC_QUEUE5_MINOR_PTR_UPDATE                                                                 0x0283
#define regVPEC_QUEUE5_MINOR_PTR_UPDATE_BASE_IDX                                                        0
#define regVPEC_QUEUE5_CD_INFO                                                                          0x0284
#define regVPEC_QUEUE5_CD_INFO_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_RB_PREEMPT                                                                       0x0285
#define regVPEC_QUEUE5_RB_PREEMPT_BASE_IDX                                                              0
#define regVPEC_QUEUE5_SKIP_CNTL                                                                        0x0286
#define regVPEC_QUEUE5_SKIP_CNTL_BASE_IDX                                                               0
#define regVPEC_QUEUE5_DOORBELL                                                                         0x0287
#define regVPEC_QUEUE5_DOORBELL_BASE_IDX                                                                0
#define regVPEC_QUEUE5_DOORBELL_OFFSET                                                                  0x0288
#define regVPEC_QUEUE5_DOORBELL_OFFSET_BASE_IDX                                                         0
#define regVPEC_QUEUE5_DUMMY0                                                                           0x0289
#define regVPEC_QUEUE5_DUMMY0_BASE_IDX                                                                  0
#define regVPEC_QUEUE5_DUMMY1                                                                           0x028a
#define regVPEC_QUEUE5_DUMMY1_BASE_IDX                                                                  0
#define regVPEC_QUEUE5_DUMMY2                                                                           0x028b
#define regVPEC_QUEUE5_DUMMY2_BASE_IDX                                                                  0
#define regVPEC_QUEUE5_DUMMY3                                                                           0x028c
#define regVPEC_QUEUE5_DUMMY3_BASE_IDX                                                                  0
#define regVPEC_QUEUE5_DUMMY4                                                                           0x028d
#define regVPEC_QUEUE5_DUMMY4_BASE_IDX                                                                  0
#define regVPEC_QUEUE5_IB_CNTL                                                                          0x02a4
#define regVPEC_QUEUE5_IB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_IB_RPTR                                                                          0x02a5
#define regVPEC_QUEUE5_IB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_IB_OFFSET                                                                        0x02a6
#define regVPEC_QUEUE5_IB_OFFSET_BASE_IDX                                                               0
#define regVPEC_QUEUE5_IB_BASE_LO                                                                       0x02a7
#define regVPEC_QUEUE5_IB_BASE_LO_BASE_IDX                                                              0
#define regVPEC_QUEUE5_IB_BASE_HI                                                                       0x02a8
#define regVPEC_QUEUE5_IB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE5_IB_SIZE                                                                          0x02a9
#define regVPEC_QUEUE5_IB_SIZE_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_CMDIB_CNTL                                                                       0x02aa
#define regVPEC_QUEUE5_CMDIB_CNTL_BASE_IDX                                                              0
#define regVPEC_QUEUE5_CMDIB_RPTR                                                                       0x02ab
#define regVPEC_QUEUE5_CMDIB_RPTR_BASE_IDX                                                              0
#define regVPEC_QUEUE5_CMDIB_OFFSET                                                                     0x02ac
#define regVPEC_QUEUE5_CMDIB_OFFSET_BASE_IDX                                                            0
#define regVPEC_QUEUE5_CMDIB_BASE_LO                                                                    0x02ad
#define regVPEC_QUEUE5_CMDIB_BASE_LO_BASE_IDX                                                           0
#define regVPEC_QUEUE5_CMDIB_BASE_HI                                                                    0x02ae
#define regVPEC_QUEUE5_CMDIB_BASE_HI_BASE_IDX                                                           0
#define regVPEC_QUEUE5_CMDIB_SIZE                                                                       0x02af
#define regVPEC_QUEUE5_CMDIB_SIZE_BASE_IDX                                                              0
#define regVPEC_QUEUE5_3DLUTIB_CNTL                                                                     0x02b0
#define regVPEC_QUEUE5_3DLUTIB_CNTL_BASE_IDX                                                            0
#define regVPEC_QUEUE5_3DLUTIB_RPTR                                                                     0x02b1
#define regVPEC_QUEUE5_3DLUTIB_RPTR_BASE_IDX                                                            0
#define regVPEC_QUEUE5_3DLUTIB_OFFSET                                                                   0x02b2
#define regVPEC_QUEUE5_3DLUTIB_OFFSET_BASE_IDX                                                          0
#define regVPEC_QUEUE5_3DLUTIB_BASE_LO                                                                  0x02b3
#define regVPEC_QUEUE5_3DLUTIB_BASE_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE5_3DLUTIB_BASE_HI                                                                  0x02b4
#define regVPEC_QUEUE5_3DLUTIB_BASE_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE5_3DLUTIB_SIZE                                                                     0x02b5
#define regVPEC_QUEUE5_3DLUTIB_SIZE_BASE_IDX                                                            0
#define regVPEC_QUEUE5_CSA_ADDR_LO                                                                      0x02b6
#define regVPEC_QUEUE5_CSA_ADDR_LO_BASE_IDX                                                             0
#define regVPEC_QUEUE5_CSA_ADDR_HI                                                                      0x02b7
#define regVPEC_QUEUE5_CSA_ADDR_HI_BASE_IDX                                                             0
#define regVPEC_QUEUE5_CONTEXT_STATUS                                                                   0x02b8
#define regVPEC_QUEUE5_CONTEXT_STATUS_BASE_IDX                                                          0
#define regVPEC_QUEUE5_DOORBELL_LOG                                                                     0x02b9
#define regVPEC_QUEUE5_DOORBELL_LOG_BASE_IDX                                                            0
#define regVPEC_QUEUE5_IB_SUB_REMAIN                                                                    0x02ba
#define regVPEC_QUEUE5_IB_SUB_REMAIN_BASE_IDX                                                           0
#define regVPEC_QUEUE5_PREEMPT                                                                          0x02bb
#define regVPEC_QUEUE5_PREEMPT_BASE_IDX                                                                 0
#define regVPEC_QUEUE5_LOG0BUFFER_CFG                                                                   0x02bc
#define regVPEC_QUEUE5_LOG0BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE5_LOG1BUFFER_CFG                                                                   0x02bd
#define regVPEC_QUEUE5_LOG1BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE6_RB_CNTL                                                                          0x02d0
#define regVPEC_QUEUE6_RB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_SCHEDULE_CNTL                                                                    0x02d1
#define regVPEC_QUEUE6_SCHEDULE_CNTL_BASE_IDX                                                           0
#define regVPEC_QUEUE6_RB_BASE                                                                          0x02d2
#define regVPEC_QUEUE6_RB_BASE_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_RB_BASE_HI                                                                       0x02d3
#define regVPEC_QUEUE6_RB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE6_RB_RPTR                                                                          0x02d4
#define regVPEC_QUEUE6_RB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_RB_RPTR_HI                                                                       0x02d5
#define regVPEC_QUEUE6_RB_RPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE6_RB_WPTR                                                                          0x02d6
#define regVPEC_QUEUE6_RB_WPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_RB_WPTR_HI                                                                       0x02d7
#define regVPEC_QUEUE6_RB_WPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE6_RB_RPTR_ADDR_HI                                                                  0x02d8
#define regVPEC_QUEUE6_RB_RPTR_ADDR_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE6_RB_RPTR_ADDR_LO                                                                  0x02d9
#define regVPEC_QUEUE6_RB_RPTR_ADDR_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE6_RB_AQL_CNTL                                                                      0x02da
#define regVPEC_QUEUE6_RB_AQL_CNTL_BASE_IDX                                                             0
#define regVPEC_QUEUE6_MINOR_PTR_UPDATE                                                                 0x02db
#define regVPEC_QUEUE6_MINOR_PTR_UPDATE_BASE_IDX                                                        0
#define regVPEC_QUEUE6_CD_INFO                                                                          0x02dc
#define regVPEC_QUEUE6_CD_INFO_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_RB_PREEMPT                                                                       0x02dd
#define regVPEC_QUEUE6_RB_PREEMPT_BASE_IDX                                                              0
#define regVPEC_QUEUE6_SKIP_CNTL                                                                        0x02de
#define regVPEC_QUEUE6_SKIP_CNTL_BASE_IDX                                                               0
#define regVPEC_QUEUE6_DOORBELL                                                                         0x02df
#define regVPEC_QUEUE6_DOORBELL_BASE_IDX                                                                0
#define regVPEC_QUEUE6_DOORBELL_OFFSET                                                                  0x02e0
#define regVPEC_QUEUE6_DOORBELL_OFFSET_BASE_IDX                                                         0
#define regVPEC_QUEUE6_DUMMY0                                                                           0x02e1
#define regVPEC_QUEUE6_DUMMY0_BASE_IDX                                                                  0
#define regVPEC_QUEUE6_DUMMY1                                                                           0x02e2
#define regVPEC_QUEUE6_DUMMY1_BASE_IDX                                                                  0
#define regVPEC_QUEUE6_DUMMY2                                                                           0x02e3
#define regVPEC_QUEUE6_DUMMY2_BASE_IDX                                                                  0
#define regVPEC_QUEUE6_DUMMY3                                                                           0x02e4
#define regVPEC_QUEUE6_DUMMY3_BASE_IDX                                                                  0
#define regVPEC_QUEUE6_DUMMY4                                                                           0x02e5
#define regVPEC_QUEUE6_DUMMY4_BASE_IDX                                                                  0
#define regVPEC_QUEUE6_IB_CNTL                                                                          0x02fc
#define regVPEC_QUEUE6_IB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_IB_RPTR                                                                          0x02fd
#define regVPEC_QUEUE6_IB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_IB_OFFSET                                                                        0x02fe
#define regVPEC_QUEUE6_IB_OFFSET_BASE_IDX                                                               0
#define regVPEC_QUEUE6_IB_BASE_LO                                                                       0x02ff
#define regVPEC_QUEUE6_IB_BASE_LO_BASE_IDX                                                              0
#define regVPEC_QUEUE6_IB_BASE_HI                                                                       0x0300
#define regVPEC_QUEUE6_IB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE6_IB_SIZE                                                                          0x0301
#define regVPEC_QUEUE6_IB_SIZE_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_CMDIB_CNTL                                                                       0x0302
#define regVPEC_QUEUE6_CMDIB_CNTL_BASE_IDX                                                              0
#define regVPEC_QUEUE6_CMDIB_RPTR                                                                       0x0303
#define regVPEC_QUEUE6_CMDIB_RPTR_BASE_IDX                                                              0
#define regVPEC_QUEUE6_CMDIB_OFFSET                                                                     0x0304
#define regVPEC_QUEUE6_CMDIB_OFFSET_BASE_IDX                                                            0
#define regVPEC_QUEUE6_CMDIB_BASE_LO                                                                    0x0305
#define regVPEC_QUEUE6_CMDIB_BASE_LO_BASE_IDX                                                           0
#define regVPEC_QUEUE6_CMDIB_BASE_HI                                                                    0x0306
#define regVPEC_QUEUE6_CMDIB_BASE_HI_BASE_IDX                                                           0
#define regVPEC_QUEUE6_CMDIB_SIZE                                                                       0x0307
#define regVPEC_QUEUE6_CMDIB_SIZE_BASE_IDX                                                              0
#define regVPEC_QUEUE6_3DLUTIB_CNTL                                                                     0x0308
#define regVPEC_QUEUE6_3DLUTIB_CNTL_BASE_IDX                                                            0
#define regVPEC_QUEUE6_3DLUTIB_RPTR                                                                     0x0309
#define regVPEC_QUEUE6_3DLUTIB_RPTR_BASE_IDX                                                            0
#define regVPEC_QUEUE6_3DLUTIB_OFFSET                                                                   0x030a
#define regVPEC_QUEUE6_3DLUTIB_OFFSET_BASE_IDX                                                          0
#define regVPEC_QUEUE6_3DLUTIB_BASE_LO                                                                  0x030b
#define regVPEC_QUEUE6_3DLUTIB_BASE_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE6_3DLUTIB_BASE_HI                                                                  0x030c
#define regVPEC_QUEUE6_3DLUTIB_BASE_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE6_3DLUTIB_SIZE                                                                     0x030d
#define regVPEC_QUEUE6_3DLUTIB_SIZE_BASE_IDX                                                            0
#define regVPEC_QUEUE6_CSA_ADDR_LO                                                                      0x030e
#define regVPEC_QUEUE6_CSA_ADDR_LO_BASE_IDX                                                             0
#define regVPEC_QUEUE6_CSA_ADDR_HI                                                                      0x030f
#define regVPEC_QUEUE6_CSA_ADDR_HI_BASE_IDX                                                             0
#define regVPEC_QUEUE6_CONTEXT_STATUS                                                                   0x0310
#define regVPEC_QUEUE6_CONTEXT_STATUS_BASE_IDX                                                          0
#define regVPEC_QUEUE6_DOORBELL_LOG                                                                     0x0311
#define regVPEC_QUEUE6_DOORBELL_LOG_BASE_IDX                                                            0
#define regVPEC_QUEUE6_IB_SUB_REMAIN                                                                    0x0312
#define regVPEC_QUEUE6_IB_SUB_REMAIN_BASE_IDX                                                           0
#define regVPEC_QUEUE6_PREEMPT                                                                          0x0313
#define regVPEC_QUEUE6_PREEMPT_BASE_IDX                                                                 0
#define regVPEC_QUEUE6_LOG0BUFFER_CFG                                                                   0x0314
#define regVPEC_QUEUE6_LOG0BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE6_LOG1BUFFER_CFG                                                                   0x0315
#define regVPEC_QUEUE6_LOG1BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE7_RB_CNTL                                                                          0x0328
#define regVPEC_QUEUE7_RB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_SCHEDULE_CNTL                                                                    0x0329
#define regVPEC_QUEUE7_SCHEDULE_CNTL_BASE_IDX                                                           0
#define regVPEC_QUEUE7_RB_BASE                                                                          0x032a
#define regVPEC_QUEUE7_RB_BASE_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_RB_BASE_HI                                                                       0x032b
#define regVPEC_QUEUE7_RB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE7_RB_RPTR                                                                          0x032c
#define regVPEC_QUEUE7_RB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_RB_RPTR_HI                                                                       0x032d
#define regVPEC_QUEUE7_RB_RPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE7_RB_WPTR                                                                          0x032e
#define regVPEC_QUEUE7_RB_WPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_RB_WPTR_HI                                                                       0x032f
#define regVPEC_QUEUE7_RB_WPTR_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE7_RB_RPTR_ADDR_HI                                                                  0x0330
#define regVPEC_QUEUE7_RB_RPTR_ADDR_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE7_RB_RPTR_ADDR_LO                                                                  0x0331
#define regVPEC_QUEUE7_RB_RPTR_ADDR_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE7_RB_AQL_CNTL                                                                      0x0332
#define regVPEC_QUEUE7_RB_AQL_CNTL_BASE_IDX                                                             0
#define regVPEC_QUEUE7_MINOR_PTR_UPDATE                                                                 0x0333
#define regVPEC_QUEUE7_MINOR_PTR_UPDATE_BASE_IDX                                                        0
#define regVPEC_QUEUE7_CD_INFO                                                                          0x0334
#define regVPEC_QUEUE7_CD_INFO_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_RB_PREEMPT                                                                       0x0335
#define regVPEC_QUEUE7_RB_PREEMPT_BASE_IDX                                                              0
#define regVPEC_QUEUE7_SKIP_CNTL                                                                        0x0336
#define regVPEC_QUEUE7_SKIP_CNTL_BASE_IDX                                                               0
#define regVPEC_QUEUE7_DOORBELL                                                                         0x0337
#define regVPEC_QUEUE7_DOORBELL_BASE_IDX                                                                0
#define regVPEC_QUEUE7_DOORBELL_OFFSET                                                                  0x0338
#define regVPEC_QUEUE7_DOORBELL_OFFSET_BASE_IDX                                                         0
#define regVPEC_QUEUE7_DUMMY0                                                                           0x0339
#define regVPEC_QUEUE7_DUMMY0_BASE_IDX                                                                  0
#define regVPEC_QUEUE7_DUMMY1                                                                           0x033a
#define regVPEC_QUEUE7_DUMMY1_BASE_IDX                                                                  0
#define regVPEC_QUEUE7_DUMMY2                                                                           0x033b
#define regVPEC_QUEUE7_DUMMY2_BASE_IDX                                                                  0
#define regVPEC_QUEUE7_DUMMY3                                                                           0x033c
#define regVPEC_QUEUE7_DUMMY3_BASE_IDX                                                                  0
#define regVPEC_QUEUE7_DUMMY4                                                                           0x033d
#define regVPEC_QUEUE7_DUMMY4_BASE_IDX                                                                  0
#define regVPEC_QUEUE7_IB_CNTL                                                                          0x0354
#define regVPEC_QUEUE7_IB_CNTL_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_IB_RPTR                                                                          0x0355
#define regVPEC_QUEUE7_IB_RPTR_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_IB_OFFSET                                                                        0x0356
#define regVPEC_QUEUE7_IB_OFFSET_BASE_IDX                                                               0
#define regVPEC_QUEUE7_IB_BASE_LO                                                                       0x0357
#define regVPEC_QUEUE7_IB_BASE_LO_BASE_IDX                                                              0
#define regVPEC_QUEUE7_IB_BASE_HI                                                                       0x0358
#define regVPEC_QUEUE7_IB_BASE_HI_BASE_IDX                                                              0
#define regVPEC_QUEUE7_IB_SIZE                                                                          0x0359
#define regVPEC_QUEUE7_IB_SIZE_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_CMDIB_CNTL                                                                       0x035a
#define regVPEC_QUEUE7_CMDIB_CNTL_BASE_IDX                                                              0
#define regVPEC_QUEUE7_CMDIB_RPTR                                                                       0x035b
#define regVPEC_QUEUE7_CMDIB_RPTR_BASE_IDX                                                              0
#define regVPEC_QUEUE7_CMDIB_OFFSET                                                                     0x035c
#define regVPEC_QUEUE7_CMDIB_OFFSET_BASE_IDX                                                            0
#define regVPEC_QUEUE7_CMDIB_BASE_LO                                                                    0x035d
#define regVPEC_QUEUE7_CMDIB_BASE_LO_BASE_IDX                                                           0
#define regVPEC_QUEUE7_CMDIB_BASE_HI                                                                    0x035e
#define regVPEC_QUEUE7_CMDIB_BASE_HI_BASE_IDX                                                           0
#define regVPEC_QUEUE7_CMDIB_SIZE                                                                       0x035f
#define regVPEC_QUEUE7_CMDIB_SIZE_BASE_IDX                                                              0
#define regVPEC_QUEUE7_3DLUTIB_CNTL                                                                     0x0360
#define regVPEC_QUEUE7_3DLUTIB_CNTL_BASE_IDX                                                            0
#define regVPEC_QUEUE7_3DLUTIB_RPTR                                                                     0x0361
#define regVPEC_QUEUE7_3DLUTIB_RPTR_BASE_IDX                                                            0
#define regVPEC_QUEUE7_3DLUTIB_OFFSET                                                                   0x0362
#define regVPEC_QUEUE7_3DLUTIB_OFFSET_BASE_IDX                                                          0
#define regVPEC_QUEUE7_3DLUTIB_BASE_LO                                                                  0x0363
#define regVPEC_QUEUE7_3DLUTIB_BASE_LO_BASE_IDX                                                         0
#define regVPEC_QUEUE7_3DLUTIB_BASE_HI                                                                  0x0364
#define regVPEC_QUEUE7_3DLUTIB_BASE_HI_BASE_IDX                                                         0
#define regVPEC_QUEUE7_3DLUTIB_SIZE                                                                     0x0365
#define regVPEC_QUEUE7_3DLUTIB_SIZE_BASE_IDX                                                            0
#define regVPEC_QUEUE7_CSA_ADDR_LO                                                                      0x0366
#define regVPEC_QUEUE7_CSA_ADDR_LO_BASE_IDX                                                             0
#define regVPEC_QUEUE7_CSA_ADDR_HI                                                                      0x0367
#define regVPEC_QUEUE7_CSA_ADDR_HI_BASE_IDX                                                             0
#define regVPEC_QUEUE7_CONTEXT_STATUS                                                                   0x0368
#define regVPEC_QUEUE7_CONTEXT_STATUS_BASE_IDX                                                          0
#define regVPEC_QUEUE7_DOORBELL_LOG                                                                     0x0369
#define regVPEC_QUEUE7_DOORBELL_LOG_BASE_IDX                                                            0
#define regVPEC_QUEUE7_IB_SUB_REMAIN                                                                    0x036a
#define regVPEC_QUEUE7_IB_SUB_REMAIN_BASE_IDX                                                           0
#define regVPEC_QUEUE7_PREEMPT                                                                          0x036b
#define regVPEC_QUEUE7_PREEMPT_BASE_IDX                                                                 0
#define regVPEC_QUEUE7_LOG0BUFFER_CFG                                                                   0x036c
#define regVPEC_QUEUE7_LOG0BUFFER_CFG_BASE_IDX                                                          0
#define regVPEC_QUEUE7_LOG1BUFFER_CFG                                                                   0x036d
#define regVPEC_QUEUE7_LOG1BUFFER_CFG_BASE_IDX                                                          0


#endif
