// SPDX-License-Identifier: GPL-2.0
/* Copyright (c) 2019 Facebook */
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>

char _license[] SEC("license") = "GPL";

#define ATTACH_PROG(__n)			\
SEC("fentry/bpf_attach_test" #__n)		\
int BPF_PROG(prog ## __n) { return 0; }

ATTACH_PROG(0)
ATTACH_PROG(1)
ATTACH_PROG(2)
ATTACH_PROG(3)
ATTACH_PROG(4)
ATTACH_PROG(5)
ATTACH_PROG(6)
ATTACH_PROG(7)
ATTACH_PROG(8)
ATTACH_PROG(9)
ATTACH_PROG(10)
ATTACH_PROG(11)
ATTACH_PROG(12)
ATTACH_PROG(13)
ATTACH_PROG(14)
ATTACH_PROG(15)
ATTACH_PROG(16)
ATTACH_PROG(17)
ATTACH_PROG(18)
ATTACH_PROG(19)
ATTACH_PROG(20)
ATTACH_PROG(21)
ATTACH_PROG(22)
ATTACH_PROG(23)
ATTACH_PROG(24)
ATTACH_PROG(25)
ATTACH_PROG(26)
ATTACH_PROG(27)
ATTACH_PROG(28)
ATTACH_PROG(29)
ATTACH_PROG(30)
ATTACH_PROG(31)
ATTACH_PROG(32)
ATTACH_PROG(33)
ATTACH_PROG(34)
ATTACH_PROG(35)
ATTACH_PROG(36)
ATTACH_PROG(37)
ATTACH_PROG(38)
ATTACH_PROG(39)
ATTACH_PROG(40)
ATTACH_PROG(41)
ATTACH_PROG(42)
ATTACH_PROG(43)
ATTACH_PROG(44)
ATTACH_PROG(45)
ATTACH_PROG(46)
ATTACH_PROG(47)
ATTACH_PROG(48)
ATTACH_PROG(49)
